# Generated by Django 5.2.12 on 2026-03-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0004_clubsettings_max_push_per_week_and_more'),
        ('students', '0004_student_assigned_trainer_student_lead_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('pipeline_type', models.CharField(choices=[('follow_up', 'Follow-up after trial'), ('win_back', 'Win-back churned')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('delay_hours', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('create_task', 'Create trainer task'), ('send_push', 'Send push notification'), ('change_status', 'Change student status')], max_length=20)),
                ('action_config', models.JSONField(default=dict)),
                ('is_terminal', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='pipelines.pipeline')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('next_step_at', models.DateTimeField(db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='pipelines.pipeline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_executions', to='students.student')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pipelines.pipelinestep')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('club', 'pipeline_type'), name='unique_active_pipeline_per_club_type'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestep',
            constraint=models.UniqueConstraint(fields=('pipeline', 'order'), name='unique_step_order'),
        ),
        migrations.AddIndex(
            model_name='pipelineexecution',
            index=models.Index(fields=['club', 'next_step_at'], name='pipelines_p_club_id_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelineexecution',
            index=models.Index(fields=['club', 'student', 'completed_at'], name='pipelines_p_club_id_95f8ca_idx'),
        ),
    ]
