# Generated by Django 5.2.12 on 2026-03-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_groupsession_checkin'),
        ('clubs', '0001_initial'),
        ('students', '0002_student_last_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tariff_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reason', models.CharField(max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='attendance.checkin')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trainings_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('scope', models.CharField(choices=[('club', 'Club'), ('location', 'Location')], default='club', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='clubs.location')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='billing.trainingtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20)),
                ('trainings_left', models.PositiveIntegerField(null=True)),
                ('trainings_used', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.CharField(max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='clubs.location')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='students.student')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.tariff')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'student', 'status'], name='billing_sub_club_id_4d50dd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingtype',
            constraint=models.UniqueConstraint(fields=('club', 'slug'), name='unique_training_type_per_club'),
        ),
    ]
