# Generated by Django 5.2.12 on 2026-03-19 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_debt_resolution_type_alter_subscription_status_and_more'),
        ('clubs', '0002_clubsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('injury', 'Injury'), ('illness', 'Illness'), ('other', 'Other')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('frozen_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frozen_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freezes', to='billing.subscription')),
            ],
            options={
                'indexes': [models.Index(fields=['subscription', 'starts_at'], name='billing_sub_subscri_27c264_idx')],
            },
        ),
    ]
