# Generated by Django 5.2.12 on 2026-03-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriptionfreeze'),
        ('clubs', '0002_clubsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'date'], name='billing_exp_club_id_8983aa_idx'), models.Index(fields=['club', 'is_recurring'], name='billing_exp_club_id_490bac_idx')],
            },
        ),
    ]
