# Generated by Django 5.2.12 on 2026-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_checkin_subscription_checkin_trainer_and_more'),
        ('billing', '0004_expense'),
        ('clubs', '0002_clubsettings'),
        ('students', '0002_student_last_visit_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='billing_sub_club_id_4d50dd_idx',
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['club', 'resolved_at'], name='billing_deb_club_id_fef295_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['club', 'student'], name='billing_deb_club_id_41528d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['club', 'student', 'status', 'expires_at'], name='billing_sub_club_id_9197a8_idx'),
        ),
    ]
