# Generated by Django 5.2.12 on 2026-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_allow_null_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='drop_in_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='trial_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('expired', 'Истёк'), ('pending', 'Ожидает'), ('frozen', 'Заморожен')], default='active', max_length=20),
        ),
    ]
