# Generated by Django 5.2.12 on 2026-04-08 08:53

from django.db import migrations, models


def backfill_kind_from_slug(apps, schema_editor):
    TrainingType = apps.get_model("billing", "TrainingType")
    for tt in TrainingType.objects.all():
        slug = (tt.slug or "").lower()
        if "personal" in slug:
            tt.kind = "personal"
        elif "mini" in slug:
            tt.kind = "mini_group"
        else:
            tt.kind = "group"
        tt.save(update_fields=["kind"])


def reverse_backfill(apps, schema_editor):
    # No-op: drop of column reverses naturally via AddField
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_drop_in_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='kind',
            field=models.CharField(
                choices=[
                    ('personal', 'Персональная'),
                    ('mini_group', 'Мини-группа'),
                    ('group', 'Групповая'),
                ],
                default='group',
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_kind_from_slug, reverse_backfill),
    ]
