# Generated by Django 5.2.12 on 2026-04-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_training_type_kind'),
        ('trainers', '0004_add_one_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='seller_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='trainers.trainer'),
        ),
    ]
