# Generated by Django 5.2.12 on 2026-04-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_payment_seller_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionfreeze',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='approved', max_length=20),
        ),
    ]
