# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_add_freeze_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="trainingtype",
            constraint=models.CheckConstraint(
                condition=models.Q(("drop_in_price__isnull", True), ("drop_in_price__gt", 0), _connector="OR"),
                name="billing_trainingtype_dropin_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariff",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)),
                name="billing_tariff_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="debt",
            constraint=models.CheckConstraint(
                condition=models.Q(("tariff_price__isnull", True), ("tariff_price__gte", 0), _connector="OR"),
                name="billing_debt_tariff_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("discount_type", "percent"), ("value__gte", 0), ("value__lte", 100))
                    | models.Q(("discount_type", "fixed"), ("value__gte", 0))
                ),
                name="billing_discount_value_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="billing_payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_amount__gt", 0)),
                name="billing_payment_original_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="billing_expense_amount_positive",
            ),
        ),
    ]
