# Generated by Codex on 2026-06-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_gradeprogressevent"),
        ("billing", "0011_money_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingtype",
            name="grade_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="training_types",
                to="grades.gradesystem",
            ),
        ),
    ]
