# Generated by Django 5.2.14 on 2026-06-04 11:38

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_subscription_paid_amount(apps, schema_editor):
    Subscription = apps.get_model("billing", "Subscription")
    Payment = apps.get_model("billing", "Payment")

    subscriptions = (
        Subscription.objects
        .filter(paid_amount__isnull=True)
        .select_related("tariff")
        .only("id", "paid_amount", "tariff__price")
    )
    for subscription in subscriptions.iterator(chunk_size=500):
        payment = (
            Payment.objects
            .filter(subscription_id=subscription.id)
            .only("amount")
            .first()
        )
        paid_amount = payment.amount if payment is not None else subscription.tariff.price
        Subscription.objects.filter(id=subscription.id).update(paid_amount=paid_amount)


def normalize_subscription_freeze_days(apps, schema_editor):
    SubscriptionFreeze = apps.get_model("billing", "SubscriptionFreeze")
    now = timezone.now()

    # Legacy code accepted zero-day freeze requests. Pending zero-day requests
    # cannot be approved safely after the new service rule, so reject them.
    SubscriptionFreeze.objects.filter(
        days__lte=0,
        status="pending",
    ).update(days=1, status="rejected", updated_at=now)

    # Historical approved/rejected rows need a positive representable duration
    # before the DB constraint can be installed.
    SubscriptionFreeze.objects.filter(days__lte=0).exclude(
        status="pending",
    ).update(days=1, updated_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_trainingtype_grade_system"),
        ("clubs", "0007_min_trainings_to_freeze"),
        ("students", "0006_task_type_attempt_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paid_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_subscription_paid_amount, migrations.RunPython.noop),
        migrations.RunPython(normalize_subscription_freeze_days, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("paid_amount__isnull", True), ("paid_amount__gt", 0), _connector="OR")
                ),
                name="billing_subscription_paid_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionfreeze",
            constraint=models.CheckConstraint(
                condition=models.Q(("days__gt", 0)),
                name="billing_subscriptionfreeze_days_positive",
            ),
        ),
    ]
