# Generated by Django 5.2.14 on 2026-06-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_debt_settlement_payment"),
        ("clubs", "0007_min_trainings_to_freeze"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtSettlementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="clubs.club",
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_events",
                        to="billing.debt",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_settlement_events",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["club", "payment", "event_type", "created_at"],
                        name="billing_deb_club_id_da1588_idx",
                    ),
                    models.Index(
                        fields=["club", "debt", "created_at"],
                        name="billing_deb_club_id_e0accd_idx",
                    ),
                ],
            },
        ),
    ]
