# Generated by Django 5.2.14 on 2026-06-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_add_freeze_decision_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtWriteOffEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField()),
                ("amount_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("debt_id_snapshot", models.PositiveBigIntegerField()),
                ("student_id_snapshot", models.PositiveBigIntegerField()),
                ("student_name_snapshot", models.CharField(max_length=255)),
                ("checkin_id_snapshot", models.PositiveBigIntegerField()),
                ("debt_reason_snapshot", models.CharField(max_length=50)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="clubs.club",
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writeoff_events",
                        to="billing.debt",
                    ),
                ),
                (
                    "written_off_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_writeoff_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["club", "decided_at"], name="billing_woff_club_decided_idx"),
                    models.Index(fields=["club", "written_off_by", "created_at"], name="billing_deb_woff_actor_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("club", "debt"),
                        name="unique_debt_writeoff_event_per_debt",
                    ),
                ],
            },
        ),
    ]
