# Generated by Django 5.2.14 on 2026-06-09 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_debtwriteoffevent'),
        ('clubs', '0007_min_trainings_to_freeze'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sale_amount_basis_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_earning_snapshot_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_rate_percent_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_trainer_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_training_type_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_training_type_kind_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='DebtLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('reserved', 'Reserved'),
                            ('confirmed', 'Confirmed'),
                            ('rejected', 'Rejected'),
                            ('attached', 'Attached'),
                            ('cancelled', 'Cancelled'),
                            ('written_off', 'Written off'),
                        ],
                        max_length=20,
                    ),
                ),
                ('reason', models.TextField(blank=True, default='')),
                ('previous_state', models.CharField(max_length=50)),
                ('new_state', models.CharField(max_length=50)),
                ('amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debt_id_snapshot', models.PositiveBigIntegerField()),
                ('student_id_snapshot', models.PositiveBigIntegerField()),
                ('student_name_snapshot', models.CharField(max_length=255)),
                ('checkin_id_snapshot', models.PositiveBigIntegerField()),
                ('debt_reason_snapshot', models.CharField(max_length=50)),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='debt_lifecycle_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'club',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)ss',
                        to='clubs.club',
                    ),
                ),
                (
                    'debt',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='lifecycle_events',
                        to='billing.debt',
                    ),
                ),
                (
                    'payment',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='debt_lifecycle_events',
                        to='billing.payment',
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='debt_lifecycle_events',
                        to='billing.subscription',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['club', 'debt', 'created_at'], name='billing_deblife_debt_idx'),
                    models.Index(fields=['club', 'event_type', 'created_at'], name='billing_deblife_type_idx'),
                    models.Index(fields=['club', 'actor', 'created_at'], name='billing_deblife_actor_idx'),
                ],
            },
        ),
    ]
