# Generated by Django 5.2.14 on 2026-06-24 04:59

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def _money(value):
    return Decimal(str(value)).quantize(Decimal("0.01"))


def _default_payout_policy(training_type_kind):
    if training_type_kind == "group":
        return "on_payment"
    if training_type_kind in {"personal", "mini_group"}:
        return "on_checkin"
    return "none"


def _unit_basis(paid_amount_basis, credits_total):
    if not credits_total:
        return None
    return _money(paid_amount_basis / Decimal(credits_total))


def backfill_package_components(apps, schema_editor):
    Tariff = apps.get_model("billing", "Tariff")
    TariffComponent = apps.get_model("billing", "TariffComponent")
    Subscription = apps.get_model("billing", "Subscription")
    SubscriptionComponent = apps.get_model("billing", "SubscriptionComponent")
    Payment = apps.get_model("billing", "Payment")

    for tariff in Tariff.objects.select_related("training_type", "location").iterator():
        payout_policy = tariff.trainer_payout_policy or _default_payout_policy(tariff.training_type.kind)
        if not tariff.trainer_payout_policy:
            Tariff.objects.filter(id=tariff.id).update(trainer_payout_policy=payout_policy)
            tariff.trainer_payout_policy = payout_policy

        if TariffComponent.objects.filter(tariff_id=tariff.id, is_active=True).exists():
            continue

        entitlement_kind = "finite_credits" if tariff.trainings_limit is not None else "unlimited"
        TariffComponent.objects.create(
            club_id=tariff.club_id,
            tariff_id=tariff.id,
            name=tariff.name,
            training_type_id=tariff.training_type_id,
            entitlement_kind=entitlement_kind,
            credits_total=tariff.trainings_limit,
            weekly_limit=None,
            scope=tariff.scope,
            location_id=tariff.location_id,
            trainer_payout_policy=payout_policy,
            paid_amount_basis=tariff.price,
            sort_order=0,
            is_active=True,
        )

    for subscription in Subscription.objects.select_related("tariff", "tariff__training_type", "location").iterator():
        tariff = subscription.tariff
        payout_policy = (
            subscription.trainer_payout_policy_snapshot
            or tariff.trainer_payout_policy
            or _default_payout_policy(tariff.training_type.kind)
        )
        if subscription.trainer_payout_policy_snapshot != payout_policy:
            Subscription.objects.filter(id=subscription.id).update(trainer_payout_policy_snapshot=payout_policy)
            subscription.trainer_payout_policy_snapshot = payout_policy

        if SubscriptionComponent.objects.filter(subscription_id=subscription.id, is_active=True).exists():
            continue

        tariff_component = (
            TariffComponent.objects.filter(tariff_id=tariff.id, is_active=True).order_by("sort_order", "id").first()
        )
        if tariff_component is None:
            continue

        payment = Payment.objects.filter(subscription_id=subscription.id).only("amount").first()
        paid_amount_basis = subscription.paid_amount or (payment.amount if payment else tariff.price)
        paid_amount_basis = _money(paid_amount_basis)

        credits_total = tariff_component.credits_total
        credits_left = None
        if tariff_component.entitlement_kind == "finite_credits":
            credits_left = subscription.trainings_left
            if credits_left is None and credits_total is not None:
                credits_left = max(credits_total - subscription.trainings_used, 0)
        SubscriptionComponent.objects.create(
            club_id=subscription.club_id,
            subscription_id=subscription.id,
            tariff_component_id=tariff_component.id,
            name_snapshot=tariff_component.name,
            training_type_id=tariff_component.training_type_id,
            entitlement_kind=tariff_component.entitlement_kind,
            credits_total=credits_total,
            credits_left=credits_left,
            credits_used=subscription.trainings_used,
            weekly_limit=tariff_component.weekly_limit,
            scope=tariff_component.scope,
            location_id=tariff_component.location_id,
            trainer_payout_policy_snapshot=tariff_component.trainer_payout_policy,
            paid_amount_basis_snapshot=paid_amount_basis,
            unit_amount_basis_snapshot=_unit_basis(paid_amount_basis, credits_total),
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_payment_package_owner_trainer'),
        ('clubs', '0007_min_trainings_to_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trainer_payout_policy_snapshot',
            field=models.CharField(blank=True, choices=[('none', 'No trainer payout'), ('on_checkin', 'Per check-in'), ('on_payment', 'On payment')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tariff',
            name='trainer_payout_policy',
            field=models.CharField(blank=True, choices=[('none', 'No trainer payout'), ('on_checkin', 'Per check-in'), ('on_payment', 'On payment')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='TariffComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('entitlement_kind', models.CharField(choices=[('finite_credits', 'Finite credits'), ('weekly_limit', 'Weekly limit'), ('unlimited', 'Unlimited')], default='finite_credits', max_length=20)),
                ('credits_total', models.PositiveIntegerField(blank=True, null=True)),
                ('weekly_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('club', 'Club'), ('location', 'Location')], default='club', max_length=20)),
                ('trainer_payout_policy', models.CharField(choices=[('none', 'No trainer payout'), ('on_checkin', 'Per check-in'), ('on_payment', 'On payment')], default='none', max_length=20)),
                ('paid_amount_basis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariff_components', to='clubs.location')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='billing.tariff')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_components', to='billing.trainingtype')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('entitlement_kind', models.CharField(choices=[('finite_credits', 'Finite credits'), ('weekly_limit', 'Weekly limit'), ('unlimited', 'Unlimited')], default='finite_credits', max_length=20)),
                ('credits_total', models.PositiveIntegerField(blank=True, null=True)),
                ('credits_left', models.PositiveIntegerField(blank=True, null=True)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('weekly_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('club', 'Club'), ('location', 'Location')], default='club', max_length=20)),
                ('trainer_payout_policy_snapshot', models.CharField(choices=[('none', 'No trainer payout'), ('on_checkin', 'Per check-in'), ('on_payment', 'On payment')], default='none', max_length=20)),
                ('paid_amount_basis_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_amount_basis_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_trainer_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sale_rate_percent_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sale_snapshot_provenance', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_components', to='clubs.location')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='billing.subscription')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_components', to='billing.trainingtype')),
                ('tariff_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_components', to='billing.tariffcomponent')),
            ],
        ),
        migrations.AddIndex(
            model_name='tariffcomponent',
            index=models.Index(fields=['club', 'tariff', 'is_active'], name='billing_tcomp_tariff_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffcomponent',
            index=models.Index(fields=['club', 'training_type'], name='billing_tcomp_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariffcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount_basis__gt', 0)), name='billing_tariffcomp_paid_basis_positive'),
        ),
        migrations.AddConstraint(
            model_name='tariffcomponent',
            constraint=models.CheckConstraint(condition=(~models.Q(('entitlement_kind', 'finite_credits')) | models.Q(('credits_total__gt', 0))), name='billing_tcomp_finite_credits_required'),
        ),
        migrations.AddConstraint(
            model_name='tariffcomponent',
            constraint=models.CheckConstraint(condition=(~models.Q(('entitlement_kind', 'weekly_limit')) | models.Q(('weekly_limit__gt', 0))), name='billing_tcomp_weekly_limit_required'),
        ),
        migrations.AddConstraint(
            model_name='tariffcomponent',
            constraint=models.CheckConstraint(condition=(~models.Q(('scope', 'location')) | models.Q(('location__isnull', False))), name='billing_tcomp_location_scope_required'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncomponent',
            index=models.Index(fields=['club', 'subscription', 'is_active'], name='billing_scomp_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncomponent',
            index=models.Index(fields=['club', 'training_type', 'is_active'], name='billing_scomp_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncomponent',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount_basis_snapshot__gt', 0)), name='billing_subcomp_paid_basis_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncomponent',
            constraint=models.CheckConstraint(condition=(~models.Q(('entitlement_kind', 'finite_credits')) | (models.Q(('credits_total__gt', 0)) & models.Q(('credits_left__isnull', False)))), name='billing_scomp_finite_credits_required'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncomponent',
            constraint=models.CheckConstraint(condition=(~models.Q(('entitlement_kind', 'weekly_limit')) | models.Q(('weekly_limit__gt', 0))), name='billing_scomp_weekly_limit_required'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncomponent',
            constraint=models.CheckConstraint(condition=(~models.Q(('scope', 'location')) | models.Q(('location__isnull', False))), name='billing_scomp_location_scope_required'),
        ),
        migrations.RunPython(
            backfill_package_components,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='subscriptioncomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('tariff_component__isnull', False)), fields=('subscription', 'tariff_component'), name='unique_subscription_tariff_component'),
        ),
    ]
