# Generated by Django 5.2.14 on 2026-06-24 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_subscription_trainer_payout_policy_snapshot_and_more'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('students', '0007_accountaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewal_chain_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='billing.subscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('online', 'Онлайн')], max_length=20),
        ),
        migrations.CreateModel(
            name='BankPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('tochka', 'Tochka')], max_length=20)),
                ('source', models.CharField(choices=[('trainer', 'Trainer'), ('owner', 'Owner'), ('admin', 'Admin'), ('student', 'Student'), ('parent', 'Parent')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('approved', 'Approved'), ('authorized', 'Authorized'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('manual_review', 'Manual review'), ('refunded', 'Refunded'), ('refunded_partially', 'Refunded partially')], default='created', max_length=30)),
                ('amount_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('purpose_snapshot', models.CharField(max_length=255)),
                ('provider_operation_id', models.CharField(blank=True, default='', max_length=120)),
                ('provider_payment_link_id', models.CharField(blank=True, default='', max_length=45)),
                ('provider_payment_url', models.URLField(blank=True, default='', max_length=1000)),
                ('provider_payment_modes', models.JSONField(blank=True, default=list)),
                ('provider_status', models.CharField(blank=True, default='', max_length=60)),
                ('provider_customer_code', models.CharField(blank=True, default='', max_length=120)),
                ('provider_merchant_id', models.CharField(blank=True, default='', max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_mode', models.CharField(choices=[('none', 'No receipt'), ('tochka_receipt', 'Tochka receipt')], default='none', max_length=30)),
                ('buyer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('receipt_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_required', max_length=30)),
                ('receipt_provider_id', models.CharField(blank=True, default='', max_length=120)),
                ('receipt_url', models.URLField(blank=True, default='', max_length=1000)),
                ('receipt_error_code', models.CharField(blank=True, default='', max_length=120)),
                ('receipt_error_message', models.TextField(blank=True, default='')),
                ('fiscal_item_snapshot', models.JSONField(blank=True, default=dict)),
                ('renewal_chain_id', models.UUIDField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=120)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_bank_payment_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bank_payment_orders', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_orders', to='billing.payment')),
                ('renewed_from_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_bank_orders', to='billing.subscription')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_payment_orders', to='students.student')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_orders', to='billing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='BankPaymentProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('tochka', 'Tochka')], max_length=20)),
                ('event_type', models.CharField(max_length=80)),
                ('provider_event_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('provider_operation_id', models.CharField(blank=True, default='', max_length=120)),
                ('provider_payment_link_id', models.CharField(blank=True, default='', max_length=45)),
                ('provider_status', models.CharField(blank=True, default='', max_length=60)),
                ('amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('failure_code', models.CharField(blank=True, default='', max_length=120)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=120)),
                ('redacted_payload_metadata', models.JSONField(blank=True, default=dict)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='billing.bankpaymentorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='bankpaymentorder',
            index=models.Index(fields=['club', 'status', 'created_at'], name='billing_bank_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentorder',
            index=models.Index(fields=['club', 'payment'], name='billing_bank_order_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentorder',
            index=models.Index(fields=['club', 'student', 'created_at'], name='billing_bank_order_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankpaymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_snapshot__gt', 0)), name='billing_bank_order_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='bankpaymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_link_id', ''), _negated=True), fields=('provider', 'provider_payment_link_id'), name='uniq_bank_order_provider_link_id'),
        ),
        migrations.AddConstraint(
            model_name='bankpaymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_operation_id', ''), _negated=True), fields=('provider', 'provider_operation_id'), name='uniq_bank_order_provider_operation'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentproviderevent',
            index=models.Index(fields=['club', 'order', 'received_at'], name='billing_bank_event_order_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentproviderevent',
            index=models.Index(fields=['club', 'processing_status', 'received_at'], name='billing_bank_event_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankpaymentproviderevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('provider', 'provider_event_id'), name='uniq_bank_event_provider_event'),
        ),
        migrations.AddConstraint(
            model_name='bankpaymentproviderevent',
            constraint=models.UniqueConstraint(condition=models.Q(('payload_hash', ''), _negated=True), fields=('provider', 'payload_hash'), name='uniq_bank_event_provider_hash'),
        ),
    ]
