# Generated by Django 5.2.14 on 2026-07-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_schedule_end_after_start'),
        ('billing', '0026_bankpaymentorderreviewevent_subscription_status'),
        ('clubs', '0007_min_trainings_to_freeze'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='conversion_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversion_payments', to='attendance.scheduleenrollment'),
        ),
        migrations.AlterField(
            model_name='bankpaymentorderreviewevent',
            name='new_subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Активен'), ('expired', 'Истёк'), ('pending', 'Ожидает'), ('frozen', 'Заморожен'), ('cancelled', 'Отменён')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankpaymentorderreviewevent',
            name='previous_subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Активен'), ('expired', 'Истёк'), ('pending', 'Ожидает'), ('frozen', 'Заморожен'), ('cancelled', 'Отменён')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('expired', 'Истёк'), ('pending', 'Ожидает'), ('frozen', 'Заморожен'), ('cancelled', 'Отменён')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentRefundCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_kind', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], max_length=20)),
                ('detected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provider_refunded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('reconciliation_required', 'Reconciliation required'), ('resolved', 'Resolved')], default='detected', max_length=40)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('legacy_review_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_case', to='billing.bankpaymentorderreviewevent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_cases', to='billing.bankpaymentorder')),
                ('provider_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_case', to='billing.bankpaymentproviderevent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_payment_refund_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('refund_kind', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], max_length=20)),
                ('provider_refunded_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_date', models.DateField()),
                ('idempotency_key', models.CharField(max_length=120)),
                ('reason', models.TextField()),
                ('entitlement_disposition', models.CharField(choices=[('kept_partial', 'Kept after partial refund'), ('keep_club_absorbs', 'Keep; club absorbs'), ('revoke_remaining', 'Revoke remaining entitlement')], max_length=32)),
                ('enrollment_disposition', models.CharField(choices=[('not_applicable', 'Not applicable'), ('kept', 'Kept'), ('cancelled_payment_created', 'Cancelled payment-created enrollment'), ('left_unlinked', 'Legacy enrollment left unlinked')], default='not_applicable', max_length=40)),
                ('personal_booking_disposition', models.CharField(choices=[('not_applicable', 'Not applicable'), ('kept', 'Kept'), ('cancelled_future', 'Cancelled future booking'), ('delivered_history_kept', 'Delivered history kept')], default='not_applicable', max_length=40)),
                ('settled_debt_disposition', models.CharField(choices=[('none', 'None'), ('absorbed', 'Settlement kept; club absorbs')], default='none', max_length=20)),
                ('settled_debts_snapshot', models.JSONField(blank=True, default=list)),
                ('entitlement_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('payroll_action_required', 'Payroll action required')], default='completed', max_length=40)),
                ('payroll_effective_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_payment_refunds', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.bankpaymentorder')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.subscription')),
                ('refund_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='billing.paymentrefundcase')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentrefundcase',
            index=models.Index(fields=['club', 'status', 'created_at'], name='billing_refcase_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefundcase',
            index=models.Index(fields=['club', 'order', 'created_at'], name='billing_refcase_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefundcase',
            constraint=models.CheckConstraint(condition=models.Q(('detected_amount__isnull', True), ('detected_amount__gt', 0), _connector='OR'), name='billing_refund_case_detected_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['club', 'accounting_date'], name='billing_refund_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['club', 'status', 'created_at'], name='billing_refund_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['club', 'payment', 'created_at'], name='billing_refund_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_payment_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.UniqueConstraint(fields=('club', 'idempotency_key'), name='unique_payment_refund_idempotency'),
        ),
    ]
