# Generated by Django 5.2.14 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0028_backfill_refund_cases_and_conversion_enrollments"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="required_tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="required_for_debts",
                to="billing.tariff",
            ),
        ),
    ]
