# Generated by Django 5.2.14 on 2026-07-27 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_scheduleenrollment_created_from_traininggroup_and_more'),
        ('billing', '0029_debt_required_tariff'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('students', '0009_student_guardian_phone'),
        ('trainers', '0014_personal_drop_in_adjustments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpaymentproviderevent',
            name='normalized_status_snapshot',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='bankpaymentproviderevent',
            name='provider_paid_at_snapshot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='conversion_group_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversion_payments', to='attendance.traininggroupmembership'),
        ),
        migrations.AddField(
            model_name='payment',
            name='group_membership_action_snapshot',
            field=models.CharField(blank=True, choices=[('new_admission', 'New admission'), ('renewal', 'Renewal')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='target_group_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_payments', to='attendance.traininggroupmembership'),
        ),
        migrations.AddField(
            model_name='payment',
            name='target_training_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_payments', to='attendance.traininggroup'),
        ),
        migrations.AlterField(
            model_name='bankpaymentproviderevent',
            name='processing_status',
            field=models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('deferred', 'Deferred')], default='received', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('conversion_group_membership__isnull', False)), fields=('conversion_group_membership',), name='uniq_payment_conversion_group_membership'),
        ),
    ]
