# Generated by Django 5.2 on 2026-08-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0030_bankpaymentproviderevent_normalized_status_snapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderWebhookDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(choices=[("mock", "Mock"), ("tochka", "Tochka")], max_length=20)),
                ("payload_hash", models.CharField(max_length=64)),
                ("provider_event_id_hash", models.CharField(blank=True, default="", max_length=64)),
                ("event_type", models.CharField(blank=True, default="", max_length=80)),
                ("provider_status", models.CharField(blank=True, default="", max_length=60)),
                ("payment_type", models.CharField(blank=True, default="", max_length=30)),
                ("amount_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("received_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, default="", max_length=120)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("matched", "Matched"),
                            ("verified_non_actionable", "Verified non-actionable"),
                            ("verified_identifier_conflict", "Verified identifier conflict"),
                        ],
                        default="received",
                        max_length=40,
                    ),
                ),
                (
                    "provider_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="global_delivery",
                        to="billing.bankpaymentproviderevent",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="providerwebhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("provider", "payload_hash"),
                name="uniq_webhook_delivery_provider_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerwebhookdelivery",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_event_id_hash", ""), _negated=True),
                fields=("provider", "provider_event_id_hash"),
                name="uniq_webhook_delivery_provider_event",
            ),
        ),
        migrations.AddIndex(
            model_name="providerwebhookdelivery",
            index=models.Index(
                fields=["provider", "outcome", "received_at"],
                name="billing_webhook_delivery_idx",
            ),
        ),
    ]
