# Generated by Django 5.2.14 on 2026-08-14 09:36

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def abort_on_duplicate_live_pending_renewals(apps, schema_editor):
    """Fail deployment before adding the partial unique constraint.

    Pending children are financial families, so selecting one automatically
    would silently orphan a payment/order.  Operators must resolve the exact
    duplicate source before this migration can install the invariant.
    """

    Subscription = apps.get_model("billing", "Subscription")
    duplicates = list(
        Subscription.objects.filter(
            renewed_from_id__isnull=False,
            status="pending",
            deleted_at__isnull=True,
        )
        .values("club_id", "renewed_from_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .order_by("club_id", "renewed_from_id")[:5]
    )
    if duplicates:
        examples = ", ".join(
            f"club={item['club_id']}/source={item['renewed_from_id']}/pending={item['total']}"
            for item in duplicates
        )
        raise RuntimeError(
            "Slice6 migration blocked by duplicate live pending subscription renewals: "
            f"{examples}. Resolve the financial families explicitly before retrying."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_payment_command_identity_and_live_personal_origins'),
        ('clubs', '0008_clubsettings_unified_client_journey_enabled'),
        ('students', '0010_student_provenance_and_intake_commands'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRenewalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField()),
                ('carry_snapshot', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RunPython(
            abort_on_duplicate_live_pending_renewals,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('renewed_from__isnull', False), ('status', 'pending')), fields=('renewed_from',), name='uniq_live_pending_subscription_renewal'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalevent',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_renewal_events', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalevent',
            name='renewed_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_finalization_events', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalevent',
            name='renewed_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_finalization_event', to='billing.subscription'),
        ),
        migrations.AddIndex(
            model_name='subscriptionrenewalevent',
            index=models.Index(fields=['club', 'renewed_from', 'created_at'], name='bill_renew_src_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionrenewalevent',
            index=models.Index(fields=['club', 'payment', 'created_at'], name='bill_renew_pay_idx'),
        ),
    ]
