# Generated by Django 5.2.14 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0044_subscription_renewal_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="renewal_source_tariff_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
