# Generated by Django 5.2.14 on 2026-09-01 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_payment_renewal_source_tariff_name_snapshot'),
        ('clubs', '0008_clubsettings_unified_client_journey_enabled'),
        ('trainers', '0014_personal_drop_in_adjustments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tariff',
            name='uniq_personal_booking_club_default',
        ),
        migrations.RemoveConstraint(
            model_name='tariff',
            name='uniq_personal_booking_location_default',
        ),
        migrations.AddField(
            model_name='tariff',
            name='personal_booking_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_booking_tariffs', to='trainers.trainer'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_personal_booking_default', True), ('personal_booking_trainer__isnull', True), ('scope', 'club')), fields=('club', 'training_type'), name='uniq_personal_booking_generic_club_default'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_personal_booking_default', True), ('personal_booking_trainer__isnull', True), ('scope', 'location')), fields=('club', 'training_type', 'location'), name='uniq_personal_booking_generic_location_default'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_personal_booking_default', True), ('personal_booking_trainer__isnull', False), ('scope', 'club')), fields=('club', 'training_type', 'personal_booking_trainer'), name='uniq_personal_booking_trainer_club_default'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_personal_booking_default', True), ('personal_booking_trainer__isnull', False), ('scope', 'location')), fields=('club', 'training_type', 'location', 'personal_booking_trainer'), name='uniq_personal_booking_trainer_location_default'),
        ),
    ]
