# Generated by Django 5.2.14 on 2026-09-08 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_personalpaymentmethodcorrection'),
        ('billing', '0046_remove_tariff_uniq_personal_booking_club_default_and_more'),
        ('clubs', '0010_commercialjourneyprotocoltransition'),
        ('students', '0010_student_provenance_and_intake_commands'),
        ('trainers', '0014_personal_drop_in_adjustments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='opening_effective_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='opening_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='opening_source_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='opening_source_namespace',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='origin',
            field=models.CharField(choices=[('ordinary', 'Обычная оплата'), ('opening', 'Перенесена')], default='ordinary', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('online', 'Онлайн'), ('unknown', 'Исторический способ неизвестен')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale_snapshot_provenance',
            field=models.CharField(blank=True, choices=[('opening_reviewed', 'Reviewed opening terms'), ('confirm_time', 'Confirm time'), ('legacy_backfill_current_state', 'Legacy backfill current state')], default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opening_effective_on__isnull', True), ('opening_provenance', {}), ('opening_source_key', ''), ('opening_source_namespace', ''), ('origin', 'ordinary')), models.Q(('opening_effective_on__isnull', False), ('origin', 'opening'), ('status', 'confirmed'), ('verified_at__isnull', False), models.Q(('opening_source_namespace', ''), _negated=True), models.Q(('opening_source_key', ''), _negated=True)), _connector='OR'), name='billing_payment_origin_terms'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method', 'unknown'), _negated=True), ('origin', 'opening'), _connector='OR'), name='billing_payment_unknown_opening_only'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'opening')), fields=('club', 'opening_source_namespace', 'opening_source_key'), name='uniq_opening_payment_source'),
        ),
    ]
