# Generated by Django 5.2.14 on 2026-09-08 04:07

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0047_payment_opening_provenance'),
        ('clubs', '0010_commercialjourneyprotocoltransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningEntitlementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_namespace', models.CharField(max_length=120)),
                ('student_source_key', models.CharField(max_length=120)),
                ('entitlement_source_key', models.CharField(max_length=120)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=20)),
                ('started_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('covered_through', models.DateTimeField()),
                ('operational_cutover', models.DateTimeField()),
                ('original_total', models.PositiveIntegerField()),
                ('original_used', models.PositiveIntegerField()),
                ('original_left', models.PositiveIntegerField()),
                ('history_only', models.BooleanField()),
                ('reviewed_input', models.JSONField()),
                ('student_transition', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_snapshot', to='billing.subscriptioncomponent')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_snapshot', to='billing.payment')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_snapshot', to='billing.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club', 'source_namespace', 'entitlement_source_key'), name='uniq_opening_entitlement_source'), models.CheckConstraint(condition=models.Q(('original_total__gt', 0), ('original_total', django.db.models.expressions.CombinedExpression(models.F('original_used'), '+', models.F('original_left')))), name='opening_original_credits_balance'), models.CheckConstraint(condition=models.Q(('operational_cutover__gt', models.F('covered_through'))), name='opening_cutover_after_coverage'), models.CheckConstraint(condition=models.Q(('expires_on__gte', models.F('started_on'))), name='opening_source_dates_ordered')],
            },
        ),
    ]
