# Generated by Django 5.2.14 on 2026-09-08 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0048_opening_entitlement_snapshot'),
        ('clubs', '0010_commercialjourneyprotocoltransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('command_key', models.CharField(max_length=120)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('expected_fingerprint', models.CharField(max_length=64)),
                ('balance_delta', models.IntegerField(default=0)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='billing.subscriptioncomponent')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensation', to='billing.subscriptioncorrection')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='billing.subscription')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'subscription', 'created_at'], name='bill_correction_history_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'command_key'), name='bill_correction_command_uniq')],
            },
        ),
    ]
