# Generated by Django 5.2.14 on 2026-09-08 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_subscription_correction_journal'),
        ('clubs', '0010_commercialjourneyprotocoltransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrefund',
            name='command_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='source',
            field=models.CharField(choices=[('provider', 'Provider'), ('manual', 'Manual or imported')], default='provider', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentrefund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.bankpaymentorder'),
        ),
        migrations.AlterField(
            model_name='paymentrefund',
            name='refund_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='billing.paymentrefundcase'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('refund_case__isnull', False), ('source', 'provider')), models.Q(('order__isnull', True), ('provider_refunded_at__isnull', True), ('refund_case__isnull', True), ('source', 'manual')), _connector='OR'), name='billing_refund_source_links'),
        ),
    ]
