# Generated by Django 5.2.14 on 2026-09-10

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0050_manual_refund_source"),
        ("clubs", "0010_commercialjourneyprotocoltransition"),
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffPriceRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("payload_fingerprint", models.CharField(max_length=64)),
                ("source_contract", models.JSONField(default=dict)),
                ("target_contract", models.JSONField(default=dict)),
                ("compatibility_snapshot", models.JSONField(default=dict)),
                ("component_mapping", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tariff_price_revisions",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="clubs.club",
                    ),
                ),
                (
                    "source_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_revision_sources",
                        to="billing.tariffcomponent",
                    ),
                ),
                (
                    "source_tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_revision_sources",
                        to="billing.tariff",
                    ),
                ),
                (
                    "target_component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_revision_target",
                        to="billing.tariffcomponent",
                    ),
                ),
                (
                    "target_tariff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_revision_target",
                        to="billing.tariff",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("club", "idempotency_key"),
                        name="uniq_tariff_price_revision_key",
                    ),
                    models.UniqueConstraint(
                        fields=("club", "source_tariff"),
                        name="uniq_tariff_price_revision_source",
                    ),
                    models.UniqueConstraint(
                        fields=("club", "target_tariff"),
                        name="uniq_tariff_price_revision_target",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(source_tariff=models.F("target_tariff")),
                        name="billing_tariff_revision_distinct_tariffs",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=("club", "source_tariff"),
                        name="billing_tariff_rev_src_idx",
                    ),
                    models.Index(
                        fields=("club", "target_tariff"),
                        name="billing_tariff_rev_tgt_idx",
                    ),
                ],
            },
        ),
    ]
