from __future__ import annotations

import json
import re
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Mapping
from datetime import UTC, datetime, timedelta
from decimal import Decimal, InvalidOperation

import jwt
from django.conf import settings
from django.core.cache import cache
from django.utils import timezone

from apps.billing.models import BankPaymentOrder
from apps.billing.payment_providers.base import (
    ProviderLinkResult,
    ProviderOperationInfo,
    ProviderRetailerInfo,
    ProviderWebhook,
    validate_sbp_only_payment_modes,
)
from apps.common.exceptions import BusinessLogicError

OFFICIAL_TOCHKA_WEBHOOK_JWK_URL = "https://enter.tochka.com/doc/openapi/static/keys/public"
_JWK_CACHE_KEY = "tochka:webhook-jwk:v1"
_JWK_REFRESH_LOCK_KEY = "tochka:webhook-jwk:refresh-lock:v1"
_JWK_REFRESH_COOLDOWN_KEY = "tochka:webhook-jwk:refresh-cooldown:v1"
_JWK_MAX_BYTES = 16 * 1024
_JWK_REQUEST_TIMEOUT_SECONDS = 3
_JWK_REFRESH_LOCK_SECONDS = 10
_PRIVATE_JWK_FIELDS = frozenset({"d", "p", "q", "dp", "dq", "qi", "oth"})
_FORBIDDEN_JWT_HEADER_FIELDS = frozenset({"jwk", "jku", "x5u", "x5c", "crit"})
_MAX_AMOUNT = Decimal("99999999.99")


class _NoRedirectHandler(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):  # noqa: N802
        return None


class TochkaPaymentProvider:
    provider = BankPaymentOrder.Provider.TOCHKA

    def create_payment_link(self, *, order: BankPaymentOrder) -> ProviderLinkResult:
        token = settings.TOCHKA_JWT_TOKEN
        customer_code = settings.TOCHKA_CUSTOMER_CODE
        if not token or not customer_code:
            raise BusinessLogicError("Токен Точки не настроен", code="tochka_credentials_missing")

        payment_modes = validate_sbp_only_payment_modes(order.provider_payment_modes)
        # The opaque state is generated by the server, stored only as a hash,
        # and sent to the provider solely as the same-origin navigation target.
        # It is not payment evidence and grants only the generic return view.
        from apps.billing.service_modules.payment_returns import create_return_state

        _raw_return_state, return_url = create_return_state(order=order)
        payload = self._create_link_payload(
            order=order,
            customer_code=customer_code,
            payment_modes=payment_modes,
            return_url=return_url,
        )
        path = (
            "/acquiring/v1.0/payments_with_receipt"
            if order.receipt_mode == BankPaymentOrder.ReceiptMode.TOCHKA_RECEIPT
            else "/acquiring/v1.0/payments"
        )
        response = self._post_json(path=path, payload=payload, token=token)
        data = response.get("Data") if isinstance(response.get("Data"), dict) else {}
        payment_url = self._payment_url_from_data(data) or self._payment_url_from_data(response)
        if not payment_url:
            raise BusinessLogicError("Точка не вернула ссылку на оплату", code="tochka_payment_link_missing")

        operation_id = str(response.get("operationId") or response.get("operation_id") or data.get("operationId") or "")
        return ProviderLinkResult(
            payment_url=str(payment_url),
            payment_link_id=order.provider_payment_link_id,
            provider_status=str(response.get("status") or data.get("status") or "CREATED"),
            operation_id=operation_id,
            customer_code=customer_code,
            merchant_id=settings.TOCHKA_MERCHANT_ID,
            payment_modes=payment_modes,
        )

    def verify_webhook(self, *, request_body: bytes, headers: Mapping[str, str]) -> ProviderWebhook:
        token = self._compact_token(request_body)
        self._validate_unverified_header(token)
        key_mode = str(getattr(settings, "TOCHKA_WEBHOOK_KEY_MODE", "") or "").strip()
        try:
            if key_mode == "pem":
                public_key = str(getattr(settings, "TOCHKA_WEBHOOK_PUBLIC_KEY", "") or "").strip()
                if not public_key:
                    raise BusinessLogicError(
                        "Публичный ключ webhook Точки не настроен",
                        code="tochka_webhook_key_missing",
                    )
                payload = self._decode_token(token=token, key=public_key)
            elif key_mode == "official_jwk":
                key = self._official_jwk_key(force_refresh=False)
                try:
                    payload = self._decode_token(token=token, key=key)
                except jwt.InvalidSignatureError:
                    key = self._official_jwk_key(force_refresh=True)
                    payload = self._decode_token(token=token, key=key)
            else:
                raise BusinessLogicError(
                    "Режим ключа webhook Точки не настроен",
                    code="tochka_webhook_key_mode_invalid",
                )
        except jwt.InvalidSignatureError as exc:
            raise BusinessLogicError(
                "Некорректная подпись webhook Точки",
                code="tochka_webhook_invalid",
            ) from exc

        try:
            return self._provider_webhook_from_payload(payload)
        except (InvalidOperation, TypeError, ValueError, OverflowError) as exc:
            raise BusinessLogicError(
                "Некорректный webhook Точки",
                code="tochka_webhook_invalid",
            ) from exc

    def normalize_status(self, *, webhook: ProviderWebhook) -> str:
        return webhook.status.strip().lower()

    def get_payment_operation_info(
        self,
        *,
        order: BankPaymentOrder,
        operation_id: str,
    ) -> ProviderOperationInfo:
        """Fetch authenticated operation evidence through the fixed Tochka API.

        This adapter is intentionally the only place that can use the bank
        credential.  Callers must invoke it outside database transactions.
        """

        if not operation_id:
            raise BusinessLogicError(
                "Для сверки с банком нужен идентификатор операции",
                code="tochka_operation_id_missing",
            )
        token = str(settings.TOCHKA_JWT_TOKEN or "").strip()
        if not token:
            raise BusinessLogicError("Токен Точки не настроен", code="tochka_credentials_missing")
        response = self._get_json(
            path=f"/acquiring/v1.0/payments/{urllib.parse.quote(operation_id, safe='')}",
            token=token,
        )
        response_data = response.get("Data")
        operations = response_data.get("Operation") if isinstance(response_data, dict) else None
        if (
            not isinstance(operations, list)
            or len(operations) != 1
            or not isinstance(operations[0], dict)
        ):
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid")
        data = operations[0]
        try:
            amount = self._parse_amount(data.get("amount"))
            paid_at = self._parse_datetime(data.get("paidAt") or data.get("paid_at"))
            payment_link_id = self._bounded_string(
                data.get("paymentLinkId") or data.get("payment_link_id"),
                max_length=45,
                field_name="paymentLinkId",
            )
            resolved_operation_id = self._bounded_string(
                data.get("operationId") or data.get("operation_id"),
                max_length=120,
                field_name="operationId",
            )
            customer_code = self._bounded_string(data.get("customerCode"), max_length=120, field_name="customerCode")
            merchant_id = self._bounded_string(data.get("merchantId"), max_length=120, field_name="merchantId")
            modes = validate_sbp_only_payment_modes(data.get("paymentMode") or data.get("paymentModes"))
        except (TypeError, ValueError, InvalidOperation) as exc:
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid") from exc
        return ProviderOperationInfo(
            status=self._bounded_string(data.get("status"), max_length=60, field_name="status"),
            operation_id=resolved_operation_id,
            payment_link_id=payment_link_id,
            payment_url=self._payment_url_from_data(data),
            amount=amount,
            customer_code=customer_code,
            merchant_id=merchant_id,
            paid_at=paid_at,
            payment_modes=modes,
        )

    def find_payment_operation_by_link(self, *, order: BankPaymentOrder) -> ProviderOperationInfo | None:
        """Bounded authenticated recovery scan for a lost create response."""

        token = str(settings.TOCHKA_JWT_TOKEN or "").strip()
        customer_code = str(order.provider_customer_code or settings.TOCHKA_CUSTOMER_CODE or "").strip()
        if not token or not customer_code or not order.link_creation_dispatched_at:
            raise BusinessLogicError("Недостаточно данных для сверки ссылки", code="tochka_recovery_not_ready")
        start = (order.link_creation_dispatched_at - timedelta(days=1)).date()
        end = timezone.now().astimezone(UTC).date()
        matches: list[ProviderOperationInfo] = []
        remaining_pages, remaining_items = 20, 10_000
        windows = 0
        while start <= end:
            windows += 1
            if windows > 4:
                raise BusinessLogicError("Сканирование операций превышает лимит", code="tochka_recovery_truncated")
            window_end = min(end, start + timedelta(days=9))
            window_matches, used_pages, used_items = self._find_payment_operation_window(
                    token=token,
                    customer_code=customer_code,
                    payment_link_id=order.provider_payment_link_id,
                    start=start,
                    end=window_end,
                    max_pages=remaining_pages,
                    max_items=remaining_items,
                )
            matches.extend(window_matches)
            remaining_pages -= used_pages
            remaining_items -= used_items
            if len(matches) > 1:
                raise BusinessLogicError("Найдено несколько операций по ссылке", code="tochka_recovery_ambiguous")
            start = window_end + timedelta(days=1)
        return matches[0] if matches else None

    def get_retailer_info(self) -> ProviderRetailerInfo:
        """Read and normalize the configured merchant from Get Retailers."""
        token = str(settings.TOCHKA_JWT_TOKEN or "").strip()
        customer_code = str(settings.TOCHKA_CUSTOMER_CODE or "").strip()
        merchant_id = str(settings.TOCHKA_MERCHANT_ID or "").strip()
        if not token or not customer_code or not merchant_id:
            raise BusinessLogicError(
                "Недостаточно данных для проверки торговой точки",
                code="tochka_retailer_readback_not_ready",
            )
        query = urllib.parse.urlencode({"customerCode": customer_code})
        response = self._get_json(
            path=f"/acquiring/v1.0/retailers?{query}",
            token=token,
        )
        data = response.get("Data")
        retailers = data.get("Retailer") if isinstance(data, dict) else None
        if (
            not isinstance(retailers, list)
            or len(retailers) > 100
            or any(not isinstance(item, dict) for item in retailers)
        ):
            raise BusinessLogicError(
                "Точка вернула некорректный список торговых точек",
                code="tochka_retailer_readback_invalid",
            )
        matches = [
            item
            for item in retailers
            if str(item.get("merchantId") or "") == merchant_id
        ]
        if len(matches) != 1:
            raise BusinessLogicError(
                "Торговая точка не найдена однозначно",
                code="tochka_retailer_readback_ambiguous",
            )
        item = matches[0]
        modes = item.get("paymentModes")
        if (
            not isinstance(item.get("isActive"), bool)
            or not isinstance(modes, list)
            or not 1 <= len(modes) <= 8
            or any(not isinstance(mode, str) or not mode or len(mode) > 32 for mode in modes)
        ):
            raise BusinessLogicError(
                "Точка вернула некорректные данные торговой точки",
                code="tochka_retailer_readback_invalid",
            )
        normalized_modes = list(dict.fromkeys(modes))
        cashbox_ready = self._parse_cashbox_ready(item.get("cashbox"))
        return ProviderRetailerInfo(
            status=self._bounded_string(item.get("status"), max_length=40, field_name="status"),
            is_active=item["isActive"],
            merchant_id=merchant_id,
            payment_modes=normalized_modes,
            cashbox_ready=cashbox_ready,
            checked_at=timezone.now(),
        )

    def _find_payment_operation_window(
        self,
        *,
        token: str,
        customer_code: str,
        payment_link_id: str,
        start,
        end,
        max_pages: int,
        max_items: int,
    ) -> tuple[list[ProviderOperationInfo], int, int]:
        matches: list[ProviderOperationInfo] = []
        if max_pages < 1 or max_items < 1:
            raise BusinessLogicError("Сканирование операций превышает лимит", code="tochka_recovery_truncated")
        seen_items = 0
        for page in range(1, max_pages + 1):
            query = urllib.parse.urlencode({
                "customerCode": customer_code,
                "fromDate": start.isoformat(),
                "toDate": end.isoformat(),
                "page": page,
                "perPage": 1000,
            })
            response = self._get_json(path=f"/acquiring/v1.0/payments?{query}", token=token)
            data, meta = response.get("Data"), response.get("Meta")
            if not isinstance(data, dict) or not isinstance(meta, dict) or not isinstance(meta.get("totalPages"), int):
                raise BusinessLogicError("Точка вернула некорректный список операций", code="tochka_recovery_invalid")
            operations = data.get("Operation")
            if not isinstance(operations, list) or len(operations) > 1000:
                raise BusinessLogicError("Точка вернула некорректный список операций", code="tochka_recovery_invalid")
            if page > meta["totalPages"] or meta["totalPages"] > max_pages:
                raise BusinessLogicError("Список операций Точки превышает лимит", code="tochka_recovery_truncated")
            seen_items += len(operations)
            if seen_items > max_items:
                raise BusinessLogicError("Список операций Точки превышает лимит", code="tochka_recovery_truncated")
            for item in operations:
                if not isinstance(item, dict):
                    raise BusinessLogicError(
                        "Точка вернула некорректный список операций", code="tochka_recovery_invalid"
                    )
                if str(item.get("paymentLinkId") or "") != payment_link_id:
                    continue
                matches.append(self._operation_info_from_data(item))
                if len(matches) > 1:
                    return matches, page, seen_items
            if page == meta["totalPages"]:
                return matches, page, seen_items
        raise BusinessLogicError("Список операций Точки превышает лимит", code="tochka_recovery_truncated")

    def _operation_info_from_data(self, data: dict) -> ProviderOperationInfo:
        try:
            return ProviderOperationInfo(
                status=self._bounded_string(data.get("status"), max_length=60, field_name="status"),
                operation_id=self._bounded_string(data.get("operationId"), max_length=120, field_name="operationId"),
                payment_link_id=self._bounded_string(
                    data.get("paymentLinkId"), max_length=45, field_name="paymentLinkId"
                ),
                payment_url=self._payment_url_from_data(data),
                amount=self._parse_amount(data.get("amount")),
                customer_code=self._bounded_string(data.get("customerCode"), max_length=120, field_name="customerCode"),
                merchant_id=self._bounded_string(data.get("merchantId"), max_length=120, field_name="merchantId"),
                paid_at=self._parse_datetime(data.get("paidAt")),
                payment_modes=validate_sbp_only_payment_modes(data.get("paymentMode") or data.get("paymentModes")),
            )
        except (TypeError, ValueError, InvalidOperation) as exc:
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_recovery_invalid") from exc

    @staticmethod
    def _parse_cashbox_ready(value) -> bool:
        if value is None or value == "":
            return False
        if not isinstance(value, str) or len(value) > 120:
            raise BusinessLogicError(
                "Точка вернула некорректные данные кассы",
                code="tochka_retailer_readback_invalid",
            )
        normalized = value.strip()
        if (
            not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{2,119}", normalized)
            or normalized.lower() in {"false", "none", "disabled", "inactive"}
        ):
            raise BusinessLogicError(
                "Точка вернула некорректные данные кассы",
                code="tochka_retailer_readback_invalid",
            )
        return True

    def _payment_url_from_data(self, data: dict) -> str:
        value = data.get("paymentLink") or data.get("paymentUrl") or data.get("payment_url") or data.get("url")
        if not value:
            return ""
        payment_url = self._bounded_string(value, max_length=1000, field_name="paymentUrl")
        parsed = urllib.parse.urlparse(payment_url)
        if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password:
            raise ValueError("paymentUrl must be an absolute HTTPS URL")
        return payment_url

    def _create_link_payload(
        self,
        *,
        order: BankPaymentOrder,
        customer_code: str,
        payment_modes: list[str],
        return_url: str,
    ) -> dict:
        payload = {
            "amount": str(order.amount_snapshot),
            "customerCode": customer_code,
            "purpose": order.purpose_snapshot,
            "paymentMode": payment_modes,
            "ttl": self._ttl_minutes(order=order),
            "paymentLinkId": order.provider_payment_link_id,
            "preAuthorization": False,
        }
        if settings.TOCHKA_MERCHANT_ID:
            payload["merchantId"] = settings.TOCHKA_MERCHANT_ID
        payload["redirectUrl"] = return_url
        payload["failRedirectUrl"] = return_url

        if order.receipt_mode == BankPaymentOrder.ReceiptMode.TOCHKA_RECEIPT:
            if not order.buyer_email:
                raise BusinessLogicError(
                    "Для фискального чека нужен email покупателя",
                    code="receipt_buyer_email_required",
                )
            payload["client"] = {
                "email": order.buyer_email,
                "phone": order.buyer_phone,
            }
            payload["taxSystemCode"] = settings.TOCHKA_RECEIPT_TAX_SYSTEM_CODE
            payload["items"] = [order.fiscal_item_snapshot]
        return {"Data": payload}

    def _ttl_minutes(self, *, order: BankPaymentOrder) -> int:
        # Reserve one minute for request transit/provider processing so the
        # provider bearer expires before the local booking/order horizon.
        remaining_seconds = (order.expires_at - timezone.now()).total_seconds()
        ttl = int((remaining_seconds - 60) // 60)
        if ttl < 1:
            raise BusinessLogicError(
                "До окончания записи недостаточно времени для безопасной ссылки СБП",
                code="bank_payment_order_ttl_too_short",
            )
        return min(44640, ttl)

    def _post_json(self, *, path: str, payload: dict, token: str) -> dict:
        url = self._api_url(path=path)
        request = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            method="POST",
        )
        try:
            opener = urllib.request.build_opener(_NoRedirectHandler())
            with opener.open(request, timeout=settings.TOCHKA_REQUEST_TIMEOUT_SECONDS) as response:
                if response.geturl() != url:
                    raise BusinessLogicError("Точка вернула неожиданный ответ", code="tochka_request_failed")
                content_type = response.headers.get("Content-Type", "")
                if not content_type.lower().startswith("application/json"):
                    raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid")
                raw_body = response.read(64 * 1024 + 1)
        except urllib.error.HTTPError as exc:
            raise BusinessLogicError("Точка отклонила создание ссылки", code="tochka_request_failed") from exc
        except urllib.error.URLError as exc:
            raise BusinessLogicError("Точка временно недоступна", code="tochka_unavailable") from exc
        if len(raw_body) > 64 * 1024:
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid")
        try:
            result = json.loads(raw_body.decode("utf-8")) if raw_body else {}
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid") from exc
        if not isinstance(result, dict):
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid")
        return result

    def _get_json(self, *, path: str, token: str) -> dict:
        url = self._api_url(path=path)
        request = urllib.request.Request(
            url,
            headers={"Authorization": f"Bearer {token}", "Accept": "application/json"},
            method="GET",
        )
        opener = urllib.request.build_opener(_NoRedirectHandler())
        try:
            with opener.open(request, timeout=settings.TOCHKA_REQUEST_TIMEOUT_SECONDS) as response:
                if response.geturl() != url:
                    raise BusinessLogicError("Точка вернула неожиданный ответ", code="tochka_request_failed")
                content_type = response.headers.get("Content-Type", "")
                if not content_type.lower().startswith("application/json"):
                    raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid")
                body = response.read(64 * 1024 + 1)
        except BusinessLogicError:
            raise
        except (OSError, urllib.error.URLError, urllib.error.HTTPError) as exc:
            raise BusinessLogicError("Точка временно недоступна", code="tochka_unavailable") from exc
        if len(body) > 64 * 1024:
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid")
        try:
            result = json.loads(body.decode("utf-8")) if body else {}
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid") from exc
        if not isinstance(result, dict):
            raise BusinessLogicError("Точка вернула некорректный ответ", code="tochka_response_invalid")
        return result

    @staticmethod
    def _api_url(*, path: str) -> str:
        base_url = str(settings.TOCHKA_API_BASE_URL or "").rstrip("/")
        parsed = urllib.parse.urlsplit(base_url)
        path_only = path.split("?", 1)[0]
        if (
            parsed.scheme != "https"
            or parsed.hostname != "enter.tochka.com"
            or parsed.port is not None
            or parsed.username is not None
            or parsed.password is not None
            or parsed.query
            or parsed.fragment
            or parsed.path != "/uapi"
            or not path_only.startswith("/acquiring/v1.0/")
        ):
            raise BusinessLogicError("Настройки API Точки некорректны", code="tochka_api_origin_invalid")
        return f"{base_url}{path}"

    def _compact_token(self, request_body: bytes) -> str:
        max_bytes = self._webhook_max_body_bytes()
        if not isinstance(request_body, bytes) or not request_body or len(request_body) > max_bytes:
            raise BusinessLogicError("Некорректный webhook Точки", code="tochka_webhook_invalid")
        try:
            token = request_body.decode("ascii")
        except UnicodeDecodeError as exc:
            raise BusinessLogicError("Некорректный webhook Точки", code="tochka_webhook_invalid") from exc
        if token != token.strip() or any(char.isspace() for char in token) or token.count(".") != 2:
            raise BusinessLogicError("Некорректный webhook Точки", code="tochka_webhook_invalid")
        return token

    def _validate_unverified_header(self, token: str) -> None:
        try:
            header = jwt.get_unverified_header(token)
        except jwt.PyJWTError as exc:
            raise BusinessLogicError("Некорректный webhook Точки", code="tochka_webhook_invalid") from exc
        if not isinstance(header, dict) or header.get("alg") != "RS256":
            raise BusinessLogicError("Некорректный webhook Точки", code="tochka_webhook_invalid")
        if _FORBIDDEN_JWT_HEADER_FIELDS.intersection(header):
            raise BusinessLogicError("Некорректный webhook Точки", code="tochka_webhook_invalid")
        try:
            self._bounded_string(header.get("kid"), max_length=120, field_name="kid")
            self._bounded_string(header.get("typ"), max_length=20, field_name="typ")
        except ValueError as exc:
            raise BusinessLogicError(
                "Некорректный webhook Точки",
                code="tochka_webhook_invalid",
            ) from exc

    def _decode_token(self, *, token: str, key) -> dict:
        try:
            payload = jwt.decode(
                token,
                key,
                algorithms=["RS256"],
                options={"verify_aud": False},
            )
        except jwt.InvalidSignatureError:
            raise
        except jwt.PyJWTError as exc:
            raise BusinessLogicError(
                "Некорректная подпись webhook Точки",
                code="tochka_webhook_invalid",
            ) from exc
        if not isinstance(payload, dict):
            raise BusinessLogicError("Некорректный webhook Точки", code="tochka_webhook_invalid")
        return payload

    def _provider_webhook_from_payload(self, payload: dict) -> ProviderWebhook:
        paid_at = self._parse_datetime(payload.get("paidAt") or payload.get("paid_at") or payload.get("date"))
        amount = self._parse_amount(payload.get("amount"))
        event_type = self._bounded_string(payload.get("webhookType"), max_length=80, field_name="webhookType")
        status = self._bounded_string(payload.get("status"), max_length=60, field_name="status")
        payment_type = self._bounded_string(payload.get("paymentType"), max_length=30, field_name="paymentType")
        payment_link_id = self._bounded_string(
            payload.get("paymentLinkId"),
            max_length=45,
            field_name="paymentLinkId",
        )
        operation_id = self._bounded_string(payload.get("operationId"), max_length=120, field_name="operationId")
        event_id = self._bounded_string(payload.get("transactionId"), max_length=120, field_name="transactionId")
        customer_code = self._bounded_string(payload.get("customerCode"), max_length=120, field_name="customerCode")
        merchant_id = self._bounded_string(payload.get("merchantId"), max_length=120, field_name="merchantId")
        return ProviderWebhook(
            event_type=event_type,
            status=status,
            payment_link_id=payment_link_id,
            amount=amount,
            operation_id=operation_id,
            event_id=event_id,
            customer_code=customer_code,
            merchant_id=merchant_id,
            paid_at=paid_at,
            metadata={
                "payment_type": payment_type,
                "has_paid_at": bool(paid_at),
            },
        )

    @staticmethod
    def _bounded_string(value, *, max_length: int, field_name: str) -> str:
        if value is None:
            return ""
        if not isinstance(value, str) or len(value) > max_length:
            raise ValueError(f"Invalid {field_name}")
        return value

    @staticmethod
    def _parse_amount(value) -> Decimal | None:
        if value is None:
            return None
        if isinstance(value, bool):
            raise ValueError("Invalid amount")
        amount = Decimal(str(value))
        if (
            not amount.is_finite()
            or amount <= 0
            or amount > _MAX_AMOUNT
            or amount.as_tuple().exponent < -2
        ):
            raise ValueError("Invalid amount")
        return amount

    @staticmethod
    def _parse_datetime(value) -> datetime | None:
        if value is None or value == "":
            return None
        if not isinstance(value, str) or len(value) > 64:
            raise ValueError("Invalid provider timestamp")
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if timezone.is_naive(parsed):
            raise ValueError("Provider timestamp must include an explicit timezone")
        now = timezone.now()
        if parsed < now - timedelta(days=45) or parsed > now + timedelta(minutes=5):
            raise ValueError("Provider timestamp outside accepted range")
        return parsed

    def _official_jwk_key(self, *, force_refresh: bool):
        cached = self._read_cached_jwk_record()
        if not force_refresh and cached is not None and cached[1]:
            return cached[0]

        if force_refresh:
            if not self._cache_add(
                _JWK_REFRESH_COOLDOWN_KEY,
                "1",
                timeout=self._refresh_cooldown_seconds(),
            ):
                raise BusinessLogicError(
                    "Ключ webhook Точки временно недоступен",
                    code="tochka_webhook_key_unavailable",
                )
            return self._fetch_validate_and_cache_jwk()

        if self._cache_add(_JWK_REFRESH_LOCK_KEY, "1", timeout=_JWK_REFRESH_LOCK_SECONDS):
            try:
                try:
                    return self._fetch_validate_and_cache_jwk()
                except BusinessLogicError:
                    if cached is not None:
                        return cached[0]
                    raise
            finally:
                self._cache_delete(_JWK_REFRESH_LOCK_KEY)

        if cached is not None:
            return cached[0]
        raise BusinessLogicError(
            "Ключ webhook Точки временно недоступен",
            code="tochka_webhook_key_unavailable",
        )

    def _read_cached_jwk_record(self):
        try:
            raw_record = cache.get(_JWK_CACHE_KEY)
        except Exception as exc:
            raise BusinessLogicError(
                "Ключ webhook Точки временно недоступен",
                code="tochka_webhook_key_unavailable",
            ) from exc
        if raw_record is None:
            return None
        try:
            record = json.loads(raw_record)
            canonical_jwk = record["jwk"]
            fetched_at = datetime.fromtimestamp(float(record["fetched_at"]), tz=UTC)
            age_seconds = (timezone.now() - fetched_at).total_seconds()
            if age_seconds < 0 or age_seconds > self._jwk_lkg_seconds():
                return None
            key, canonical_jwk = self._validated_jwk(canonical_jwk)
            return key, age_seconds <= self._jwk_cache_seconds()
        except (KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
            raise BusinessLogicError(
                "Ключ webhook Точки временно недоступен",
                code="tochka_webhook_key_unavailable",
            ) from exc

    def _fetch_validate_and_cache_jwk(self):
        jwk_document = self._fetch_official_jwk()
        try:
            key, canonical_jwk = self._validated_jwk(jwk_document)
        except (TypeError, ValueError, jwt.PyJWTError) as exc:
            raise BusinessLogicError(
                "Ключ webhook Точки временно недоступен",
                code="tochka_webhook_key_unavailable",
            ) from exc
        record = json.dumps(
            {
                "jwk": canonical_jwk,
                "fetched_at": timezone.now().timestamp(),
            },
            separators=(",", ":"),
            sort_keys=True,
        )
        try:
            cache.set(_JWK_CACHE_KEY, record, timeout=self._jwk_lkg_seconds())
        except Exception as exc:
            raise BusinessLogicError(
                "Ключ webhook Точки временно недоступен",
                code="tochka_webhook_key_unavailable",
            ) from exc
        return key

    def _fetch_official_jwk(self) -> dict:
        request = urllib.request.Request(
            OFFICIAL_TOCHKA_WEBHOOK_JWK_URL,
            headers={"Accept": "application/json"},
            method="GET",
        )
        opener = urllib.request.build_opener(_NoRedirectHandler())
        try:
            with opener.open(request, timeout=_JWK_REQUEST_TIMEOUT_SECONDS) as response:
                if response.geturl() != OFFICIAL_TOCHKA_WEBHOOK_JWK_URL:
                    raise BusinessLogicError(
                        "Ключ webhook Точки временно недоступен",
                        code="tochka_webhook_key_unavailable",
                    )
                body = response.read(_JWK_MAX_BYTES + 1)
        except BusinessLogicError:
            raise
        except (OSError, urllib.error.URLError, urllib.error.HTTPError) as exc:
            raise BusinessLogicError(
                "Ключ webhook Точки временно недоступен",
                code="tochka_webhook_key_unavailable",
            ) from exc
        if len(body) > _JWK_MAX_BYTES:
            raise BusinessLogicError(
                "Ключ webhook Точки временно недоступен",
                code="tochka_webhook_key_unavailable",
            )
        try:
            document = json.loads(body.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise BusinessLogicError(
                "Ключ webhook Точки временно недоступен",
                code="tochka_webhook_key_unavailable",
            ) from exc
        return document

    @staticmethod
    def _validated_jwk(document):
        if isinstance(document, str):
            document = json.loads(document)
        if (
            not isinstance(document, dict)
            or document.get("kty") != "RSA"
            or not isinstance(document.get("n"), str)
            or not isinstance(document.get("e"), str)
            or "keys" in document
            or _PRIVATE_JWK_FIELDS.intersection(document)
            or (document.get("alg") not in (None, "RS256"))
            or (document.get("use") not in (None, "sig"))
            or (document.get("key_ops") not in (None, ["verify"]))
        ):
            raise ValueError("Invalid Tochka public JWK")
        canonical = json.dumps(
            {"e": document["e"], "kty": "RSA", "n": document["n"]},
            separators=(",", ":"),
            sort_keys=True,
        )
        key = jwt.algorithms.RSAAlgorithm.from_jwk(canonical)
        if getattr(key, "key_size", 0) < 2048 or hasattr(key, "private_numbers"):
            raise ValueError("Invalid Tochka public JWK")
        return key, canonical

    @staticmethod
    def _cache_add(key: str, value: str, *, timeout: int) -> bool:
        try:
            return bool(cache.add(key, value, timeout=timeout))
        except Exception as exc:
            raise BusinessLogicError(
                "Ключ webhook Точки временно недоступен",
                code="tochka_webhook_key_unavailable",
            ) from exc

    @staticmethod
    def _cache_delete(key: str) -> None:
        try:
            cache.delete(key)
        except Exception:
            # The bounded lock expires on its own. The verified delivery still
            # succeeds without exposing cache details or extending the lock.
            pass

    @staticmethod
    def _bounded_setting(name: str, *, minimum: int, maximum: int) -> int:
        value = int(getattr(settings, name))
        if not minimum <= value <= maximum:
            raise BusinessLogicError(
                "Настройки ключа webhook Точки некорректны",
                code="tochka_webhook_key_mode_invalid",
            )
        return value
    def _jwk_cache_seconds(self) -> int:
        return self._bounded_setting(
            "TOCHKA_WEBHOOK_JWK_CACHE_SECONDS",
            minimum=60,
            maximum=86400,
        )

    def _jwk_lkg_seconds(self) -> int:
        current = self._jwk_cache_seconds()
        value = self._bounded_setting(
            "TOCHKA_WEBHOOK_JWK_LKG_SECONDS",
            minimum=current,
            maximum=604800,
        )
        return value

    def _refresh_cooldown_seconds(self) -> int:
        return self._bounded_setting(
            "TOCHKA_WEBHOOK_JWK_REFRESH_COOLDOWN_SECONDS",
            minimum=10,
            maximum=600,
        )

    @staticmethod
    def _webhook_max_body_bytes() -> int:
        value = int(settings.TOCHKA_WEBHOOK_MAX_BODY_BYTES)
        if not 1024 <= value <= 65536:
            raise BusinessLogicError(
                "Настройки webhook Точки некорректны",
                code="tochka_webhook_key_mode_invalid",
            )
        return value
