# Generated by Django 5.2.12 on 2026-03-19 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_child', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('trial', 'Trial'), ('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned'), ('lost', 'Lost')], default='lead', max_length=20)),
                ('source', models.CharField(choices=[('recommendation', 'Recommendation'), ('instagram', 'Instagram'), ('vk', 'VK'), ('signboard', 'Signboard'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20)),
                ('contraindications', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_notes', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['club', 'status'], name='students_st_club_id_47e94b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['club', 'phone'], name='students_st_club_id_52d905_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('club', 'phone'), name='unique_student_phone_per_club'),
        ),
    ]
