# Generated by Django 5.2.12 on 2026-03-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
