# Generated by Django 5.2.12 on 2026-03-23 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_clubsettings_max_push_per_week_and_more'),
        ('students', '0003_student_parent_user_parentinvite'),
        ('trainers', '0002_trainerearning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='trainers.trainer'),
        ),
        migrations.AddField(
            model_name='student',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial_booked', 'Trial Booked'), ('trial_done', 'Trial Done'), ('thinking', 'Thinking')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('expensive', 'Too expensive'), ('didnt_like_training', "Didn't like training"), ('didnt_like_trainer', "Didn't like trainer"), ('too_far', 'Too far'), ('no_time', 'No time'), ('chose_other_club', 'Chose another club'), ('injury_health', 'Injury/health'), ('child_didnt_like', "Child didn't like"), ('changed_mind', 'Changed mind'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='trial_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['club', 'lead_status'], name='students_st_club_id_fc4572_idx'),
        ),
    ]
