# Generated by Django 5.2.12 on 2026-04-10 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('contacted', 'Связались'), ('trial_booked', 'Пробное назначено'), ('trial_done', 'Пробное проведено'), ('thinking', 'Думает')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('expensive', 'Дорого'), ('didnt_like_training', 'Не понравились тренировки'), ('didnt_like_trainer', 'Не понравился тренер'), ('too_far', 'Далеко'), ('no_time', 'Нет времени'), ('chose_other_club', 'Выбрал другой клуб'), ('injury_health', 'Травма / здоровье'), ('child_didnt_like', 'Ребёнку не понравилось'), ('changed_mind', 'Передумал'), ('other', 'Другое')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (10-15 цифр, можно с +)', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='source',
            field=models.CharField(choices=[('recommendation', 'Рекомендация'), ('instagram', 'Instagram'), ('vk', 'ВКонтакте'), ('signboard', 'Вывеска'), ('website', 'Сайт'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('lead', 'Лид'), ('trial', 'Пробное'), ('active', 'Активен'), ('at_risk', 'В риске'), ('churned', 'Ушёл'), ('lost', 'Потерян')], default='lead', max_length=20),
        ),
    ]
