# Generated by Django 5.2.14 on 2026-06-19 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_min_trainings_to_freeze'),
        ('students', '0006_task_type_attempt_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reset', 'Reset')], default='open', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('temporary_credential_revealed_at', models.DateTimeField(blank=True, null=True)),
                ('setup_token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_student_account_accesses', to=settings.AUTH_USER_MODEL)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_student_account_accesses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_accesses', to='students.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_account_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'user', 'role'], name='students_ac_club_id_b59893_idx'), models.Index(fields=['club', 'student', 'role'], name='students_ac_club_id_8bb07e_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'student', 'role'), name='unique_account_access_student_role_per_club')],
            },
        ),
    ]
