# Generated by Django 5.2.14 on 2026-09-08 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_commercialjourneyprotocoltransition'),
        ('students', '0010_student_provenance_and_intake_commands'),
        ('trainers', '0015_opening_package_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='student_lead_requires_lead_status',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'lead'), _negated=True), ('lead_status__isnull', False), ('became_student_at__isnull', False), _connector='OR'), name='student_lead_requires_lead_status'),
        ),
    ]
