# Generated by Django 5.2.14 on 2026-09-08 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_commercialjourneyprotocoltransition'),
        ('students', '0011_accepted_history_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('source_namespace', models.CharField(max_length=120)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('source_file', models.CharField(blank=True, max_length=80)),
                ('prepared_file', models.CharField(blank=True, max_length=80)),
                ('expires_at', models.DateTimeField()),
                ('apply_channel', models.CharField(blank=True, max_length=24)),
                ('expected_effects', models.JSONField(default=dict)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('apply_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('entitlement', 'Абонемент'), ('settlement_opening', 'Начальный расчёт'), ('settlement_payout', 'Выплата')], max_length=24)),
                ('source_key', models.CharField(max_length=120)),
                ('source_row', models.PositiveIntegerField()),
                ('source_sheet', models.CharField(max_length=40)),
                ('source_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('errors', models.JSONField(default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='students.openingimportbatch')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningImportPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('selection_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('selection', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previews', to='students.openingimportbatch')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='openingimportbatch',
            name='accepted_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.openingimportpreview'),
        ),
        migrations.CreateModel(
            name='OpeningImportItemReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_namespace', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('entitlement', 'Абонемент'), ('settlement_opening', 'Начальный расчёт'), ('settlement_payout', 'Выплата')], max_length=24)),
                ('source_key', models.CharField(max_length=120)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('domain_result', models.JSONField(default=dict)),
                ('channel', models.CharField(max_length=24)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='students.openingimportitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club', 'source_namespace', 'kind', 'source_key'), name='unique_opening_import_source_receipt')],
            },
        ),
    ]
