# Generated by Django 5.2.12 on 2026-03-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_clubsettings'),
        ('students', '0003_student_parent_user_parentinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('children', 'Children only'), ('adults', 'Adults only'), ('all', 'All students')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_provided', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, default='', upload_to='documents/%Y/%m/')),
                ('is_private', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_documents', to='documents.documenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('club', 'name'), name='unique_active_doctype_name_per_club'),
        ),
        migrations.AddConstraint(
            model_name='studentdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('club', 'student', 'document_type'), name='unique_student_document_per_type'),
        ),
    ]
