# Generated by Django 5.2.12 on 2026-03-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freeze_enabled', models.BooleanField(default=True)),
                ('freeze_max_days', models.PositiveIntegerField(default=30)),
                ('freeze_max_count', models.PositiveIntegerField(blank=True, null=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='clubs.club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
