# Generated by Django 5.2.12 on 2026-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='feedback_delay_hours',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
