# Generated by Django 5.2.12 on 2026-03-23 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubsettings_feedback_delay_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='max_push_per_week',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
    ]
