# Generated by Django 5.2.12 on 2026-03-23 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_clubsettings_max_push_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='accent_color',
            field=models.CharField(default='#FF6B00', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be hex color #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='club_name_display',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be hex color #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
