# Generated by Django 5.2.12 on 2026-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubsettings_branding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
    ]
