# Generated by Django 5.2.12 on 2026-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubsettings_logo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='min_trainings_to_freeze',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
