# Generated by Django 5.2.12 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_min_trainings_to_freeze"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubsettings",
            name="unified_client_journey_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
