# Generated by Django 5.2.12 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_clubsettings_unified_client_journey_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubsettings",
            name="commercial_journey_protocol_version",
            field=models.CharField(
                choices=[
                    ("v1", "Commercial journey protocol v1"),
                    ("v2", "Commercial journey protocol v2"),
                ],
                default="v1",
                max_length=2,
            ),
        ),
    ]
