# Generated by Django 5.2.12 on 2026-03-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0003_clubsettings_feedback_delay_hours'),
        ('students', '0003_student_parent_user_parentinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Опрос после пробной', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('rating', 'Rating 1-5'), ('yes_no', 'Yes/No'), ('text', 'Text comment')], max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='feedback.feedbackform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='feedback.feedbackform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_responses', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='feedback.feedbackquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='feedback.feedbackresponse')),
            ],
        ),
        migrations.AddConstraint(
            model_name='feedbackform',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('club',), name='unique_active_form_per_club'),
        ),
        migrations.AddConstraint(
            model_name='feedbackquestion',
            constraint=models.UniqueConstraint(fields=('form', 'order'), name='unique_question_order_per_form'),
        ),
        migrations.AddConstraint(
            model_name='feedbackresponse',
            constraint=models.UniqueConstraint(fields=('club', 'form', 'student'), name='unique_response_per_student_per_form'),
        ),
        migrations.AddConstraint(
            model_name='feedbackanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_question'),
        ),
    ]
