# Generated by Django 5.2.12 on 2026-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_clubsettings_max_push_per_week_and_more'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedbackform',
            name='unique_active_form_per_club',
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='trigger_type',
            field=models.CharField(choices=[('trial', 'After trial'), ('churned', 'Churned student')], default='trial', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='feedbackform',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('club', 'trigger_type'), name='unique_active_form_per_club_trigger'),
        ),
    ]
