# Views package -- re-export all views for URL routing compatibility
from apps.htmx_admin.views.billing import (
    approve_freeze_view,
    bank_payment_order_reconcile_action,
    bank_payment_order_review_action,
    create_subscription_view,
    debtor_export,
    debtor_list,
    debtor_write_off_action,
    freeze_subscription_view,
    payment_list,
    payment_refund_case_approve_action,
    payment_refund_payroll_action,
    reject_freeze_view,
    subscription_list,
    unfreeze_subscription_view,
    verify_payment_action,
)
from apps.htmx_admin.views.dashboard import (
    admin_login,
    admin_logout,
    dashboard_home,
    dashboard_metrics_partial,
)
from apps.htmx_admin.views.notifications import push_notifications, push_preview
from apps.htmx_admin.views.onboarding import (
    onboarding_finish,
    onboarding_skip,
    onboarding_step,
    onboarding_wizard,
)
from apps.htmx_admin.views.reports import expense_create, expense_delete, pnl_export_excel, pnl_report
from apps.htmx_admin.views.retention import retention_task_comments, retention_tasks
from apps.htmx_admin.views.schedule import (
    checkin_cancel_admin,
    exception_revert,
    personal_drop_in_attendance_correction,
    schedule_create,
    schedule_edit,
    schedule_enrollment_cancel_admin,
    schedule_enrollment_freeze_admin,
    schedule_enrollment_transfer_admin,
    schedule_enrollment_unfreeze_admin,
    schedule_view,
    session_cancel,
    session_detail,
    session_enroll,
    session_reschedule,
    session_substitute,
)
from apps.htmx_admin.views.settings import (
    discount_form,
    discount_toggle,
    document_type_form,
    document_type_toggle,
    grade_delete,
    grade_form,
    grade_system_delete,
    grade_system_form,
    kiosk_deactivate,
    kiosk_generate_pin,
    location_delete,
    location_form,
    notification_template_form,
    notification_template_toggle,
    settings_billing_view,
    settings_catalog_view,
    settings_documents_view,
    settings_general_view,
    settings_kiosk_view,
    settings_notifications_view,
    settings_redirect,
    tariff_archive_view,
    tariff_form,
    tariff_price_revision_form,
    tariff_toggle,
    training_type_form,
    training_type_toggle,
)
from apps.htmx_admin.views.students import (
    import_confirm,
    import_upload,
    student_account_access_open,
    student_account_access_reset,
    student_add_note,
    student_card,
    student_create,
    student_document_mark,
    student_document_open,
    student_document_upload,
    student_edit,
    student_list,
    student_parent_invite,
    student_status_change,
)
from apps.htmx_admin.views.trainers import (
    session_checkins,
    trainer_create,
    trainer_detail,
    trainer_earning_correction,
    trainer_edit,
    trainer_list,
    trainer_payroll_close_period,
    trainer_rates,
    trainer_salary,
    trainer_sessions,
)

__all__ = [
    # Dashboard
    "dashboard_home",
    "dashboard_metrics_partial",
    "admin_login",
    "admin_logout",
    # Students
    "student_list",
    "student_create",
    "student_card",
    "student_document_mark",
    "student_document_upload",
    "student_document_open",
    "import_upload",
    "import_confirm",
    "student_status_change",
    "student_parent_invite",
    "student_add_note",
    "student_account_access_open",
    "student_account_access_reset",
    "student_edit",
    # Schedule
    "checkin_cancel_admin",
    "exception_revert",
    "personal_drop_in_attendance_correction",
    "schedule_create",
    "schedule_enrollment_cancel_admin",
    "schedule_enrollment_freeze_admin",
    "schedule_enrollment_transfer_admin",
    "schedule_enrollment_unfreeze_admin",
    "schedule_edit",
    "schedule_view",
    "session_detail",
    "session_enroll",
    "session_cancel",
    "session_reschedule",
    "session_substitute",
    "session_checkins",
    # Billing
    "debtor_list",
    "debtor_export",
    "debtor_write_off_action",
    "payment_list",
    "payment_refund_case_approve_action",
    "payment_refund_payroll_action",
    "verify_payment_action",
    "bank_payment_order_reconcile_action",
    "bank_payment_order_review_action",
    "subscription_list",
    "create_subscription_view",
    "freeze_subscription_view",
    "approve_freeze_view",
    "reject_freeze_view",
    "unfreeze_subscription_view",
    # Trainers
    "trainer_list",
    "trainer_create",
    "trainer_detail",
    "trainer_earning_correction",
    "trainer_edit",
    "trainer_rates",
    "trainer_salary",
    "trainer_sessions",
    "trainer_payroll_close_period",
    # Reports
    "pnl_report",
    "pnl_export_excel",
    "expense_create",
    "expense_delete",
    # Onboarding
    "onboarding_wizard",
    "onboarding_step",
    "onboarding_skip",
    "onboarding_finish",
    # Retention
    "retention_tasks",
    "retention_task_comments",
    # Notifications
    "push_notifications",
    "push_preview",
    # Settings
    "settings_redirect",
    "settings_general_view",
    "settings_billing_view",
    "tariff_archive_view",
    "settings_catalog_view",
    "settings_documents_view",
    "settings_notifications_view",
    "settings_kiosk_view",
    "kiosk_generate_pin",
    "kiosk_deactivate",
    # Notification templates
    "notification_template_form",
    "notification_template_toggle",
    # Catalog CRUD
    "location_form",
    "location_delete",
    "grade_system_form",
    "grade_system_delete",
    "grade_form",
    "grade_delete",
    "document_type_form",
    "document_type_toggle",
    # Billing CRUD
    "tariff_form",
    "tariff_price_revision_form",
    "tariff_toggle",
    "training_type_form",
    "training_type_toggle",
    "discount_form",
    "discount_toggle",
]
