# Generated by Django 5.2.12 on 2026-03-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0004_clubsettings_max_push_per_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.IntegerField(default=1)),
                ('data', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_completed', False)), fields=('club',), name='unique_active_draft_per_club')],
            },
        ),
    ]
