# Generated by Django 5.2.12 on 2026-03-19 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_group', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('rate_personal', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('rate_mini_group', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_locations', to='clubs.location')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_locations', to='trainers.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='locations',
            field=models.ManyToManyField(related_name='trainers', through='trainers.TrainerLocation', to='clubs.location'),
        ),
        migrations.AddConstraint(
            model_name='trainerlocation',
            constraint=models.UniqueConstraint(fields=('trainer', 'location'), name='unique_trainer_per_location'),
        ),
    ]
