# Generated by Django 5.2.12 on 2026-03-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_checkin_subscription_checkin_trainer_and_more'),
        ('clubs', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earning_type', models.CharField(choices=[('group', 'Group'), ('personal', 'Personal'), ('mini_group', 'Mini Group')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='attendance.checkin')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='trainers.trainer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
