# Generated by Django 5.2.12 on 2026-03-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainerearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerlocation',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_locations', to='trainers.trainer'),
        ),
    ]
