# Generated by Django 5.2.12 on 2026-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainerlocation_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerearning',
            name='earning_type',
            field=models.CharField(choices=[('group', 'Групповое'), ('personal', 'Персональное'), ('mini_group', 'Мини-группа')], max_length=20),
        ),
    ]
