# Generated by Django 5.2.12 on 2026-04-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_one_time_date'),
        ('billing', '0009_payment_seller_trainer'),
        ('clubs', '0006_clubsettings_logo_file'),
        ('trainers', '0004_add_one_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerearning',
            name='earning_source',
            field=models.CharField(choices=[('checkin', 'Чек-ин'), ('sale', 'Продажа')], default='checkin', max_length=10),
        ),
        migrations.AddField(
            model_name='trainerearning',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='billing.payment'),
        ),
        migrations.AlterField(
            model_name='trainerearning',
            name='checkin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.checkin'),
        ),
        migrations.AddConstraint(
            model_name='trainerearning',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment',), name='unique_sale_earning_per_payment'),
        ),
    ]
