# Generated by Django 5.2.12 on 2026-04-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_payment_seller_trainer'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('trainers', '0005_trainerearning_earning_source_trainerearning_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_rates', to='clubs.location')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='trainers.trainer')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_rates', to='billing.trainingtype')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'trainer', 'location', 'training_type'], name='trainers_tr_club_id_c7d24c_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'trainer', 'location', 'training_type'), name='unique_rate_per_trainer_location_type')],
            },
        ),
    ]
