# Generated by Django 5.2.14 on 2026-06-16 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_package_allocations(apps, schema_editor):
    Payment = apps.get_model("billing", "Payment")
    TrainerPackageAllocation = apps.get_model("trainers", "TrainerPackageAllocation")

    existing_subscription_ids = set(
        TrainerPackageAllocation.objects.filter(is_active=True).values_list(
            "subscription_id",
            flat=True,
        )
    )
    now = timezone.now()
    rows = []
    payments = (
        Payment.objects.filter(
            seller_trainer_id__isnull=False,
            subscription_id__isnull=False,
            subscription__deleted_at__isnull=True,
            subscription__status__in=["active", "frozen"],
            subscription__tariff__training_type__kind__in=["personal", "mini_group"],
        )
        .select_related("subscription", "subscription__tariff", "subscription__tariff__training_type")
        .order_by("id")
    )

    for payment in payments.iterator():
        subscription = payment.subscription
        if subscription.id in existing_subscription_ids:
            continue
        rows.append(
            TrainerPackageAllocation(
                club_id=payment.club_id,
                subscription_id=subscription.id,
                payment_id=payment.id,
                student_id=subscription.student_id,
                tariff_id=subscription.tariff_id,
                training_type_id=subscription.tariff.training_type_id,
                owner_trainer_id=payment.seller_trainer_id,
                source="payment",
                sessions_total_snapshot=subscription.tariff.trainings_limit,
                sessions_remaining_snapshot=subscription.trainings_left,
                amount_snapshot=subscription.paid_amount or payment.amount or subscription.tariff.price,
                is_active=True,
                created_at=now,
                updated_at=now,
                activated_at=now,
                created_by_id=payment.recorded_by_id,
            )
        )
        existing_subscription_ids.add(subscription.id)

    TrainerPackageAllocation.objects.bulk_create(rows, batch_size=500, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0009_kiosk_activation_hardening"),
        ("billing", "0020_payment_sale_snapshot_provenance"),
        ("clubs", "0007_min_trainings_to_freeze"),
        ("students", "0006_task_type_attempt_count"),
        ("trainers", "0008_remove_legacy_rate_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerEarningAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_basis_snapshot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payable_amount_delta", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("affects_payroll", models.BooleanField(default=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit"), ("info", "Info")],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("package_transfer", "Package transfer"),
                            ("manual_adjustment", "Manual adjustment"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="%(class)ss", to="clubs.club"
                    ),
                ),
                (
                    "counterparty_trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counterparty_earning_adjustments",
                        to="trainers.trainer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_earning_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="trainers.trainerearningadjustment",
                    ),
                ),
                (
                    "source_checkin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_earning_adjustments",
                        to="attendance.checkin",
                    ),
                ),
                (
                    "source_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_earning_adjustments",
                        to="billing.payment",
                    ),
                ),
                (
                    "source_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_earning_adjustments",
                        to="billing.subscription",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earning_adjustments",
                        to="trainers.trainer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["club", "trainer", "effective_date", "kind"], name="trainers_tr_club_id_c24106_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "package_transfer"), ("source_checkin__isnull", False)),
                        fields=("club", "source_checkin", "trainer", "kind", "direction"),
                        name="unique_package_transfer_adjustment",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "reversal"), ("reversal_of__isnull", False)),
                        fields=("club", "reversal_of", "kind"),
                        name="unique_package_transfer_reversal",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrainerPackageAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("manual_subscription", "Manual subscription"),
                            ("manual_transfer", "Manual transfer"),
                        ],
                        default="manual_subscription",
                        max_length=32,
                    ),
                ),
                ("sessions_total_snapshot", models.PositiveIntegerField(blank=True, null=True)),
                ("sessions_remaining_snapshot", models.PositiveIntegerField(blank=True, null=True)),
                ("amount_snapshot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("transfer_reason", models.TextField(blank=True, default="")),
                ("note", models.TextField(blank=True, default="")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="%(class)ss", to="clubs.club"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_trainer_package_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deactivated_trainer_package_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_package_allocations",
                        to="trainers.trainer",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_allocations",
                        to="billing.payment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_package_allocations",
                        to="students.student",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_allocations",
                        to="billing.subscription",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_package_allocations",
                        to="billing.tariff",
                    ),
                ),
                (
                    "training_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_package_allocations",
                        to="billing.trainingtype",
                    ),
                ),
                (
                    "transferred_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="trainers.trainerpackageallocation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["club", "owner_trainer", "is_active"], name="trainers_tr_club_id_1694dd_idx"),
                    models.Index(fields=["club", "subscription", "created_at"], name="trainers_tr_club_id_586225_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("club", "subscription"),
                        name="unique_active_trainer_package_allocation",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_package_allocations, migrations.RunPython.noop),
    ]
