# Generated by Django 5.2.14 on 2026-06-21 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_personal_availability_slot'),
        ('billing', '0021_payment_package_owner_trainer'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('trainers', '0009_trainer_package_compensation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerearningadjustment',
            name='correction_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerearningadjustment',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='trainerearningadjustment',
            index=models.Index(fields=['club', 'correction_group_id'], name='trainers_tr_club_id_05a175_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerearningadjustment',
            index=models.Index(fields=['club', 'idempotency_key'], name='trainers_tr_club_id_d5c2a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainerearningadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_group_id__isnull', False), ('kind', 'manual_adjustment')), fields=('club', 'correction_group_id', 'direction'), name='unique_manual_adjustment_group_direction'),
        ),
        migrations.AddConstraint(
            model_name='trainerearningadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'manual_adjustment'), models.Q(('idempotency_key', ''), _negated=True)), fields=('club', 'idempotency_key', 'kind', 'direction'), name='unique_manual_adjustment_idempotency_direction'),
        ),
        migrations.AddConstraint(
            model_name='trainerearningadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'debit'), ('kind', 'manual_adjustment'), ('source_checkin__isnull', False)), fields=('club', 'source_checkin', 'trainer', 'kind', 'direction'), name='unique_manual_adjustment_checkin_debit'),
        ),
        migrations.AddConstraint(
            model_name='trainerearningadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'debit'), ('kind', 'manual_adjustment'), ('source_payment__isnull', False)), fields=('club', 'source_payment', 'trainer', 'kind', 'direction'), name='unique_manual_adjustment_payment_debit'),
        ),
    ]
