# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_min_trainings_to_freeze"),
        ("trainers", "0010_trainer_earning_manual_correction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerPayrollPeriodClose",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                ("salary_total_snapshot", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("trainer_totals_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="clubs.club",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_payroll_period_closes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="trainerpayrollperiodclose",
            index=models.Index(fields=["club", "period_start", "period_end"], name="trainers_tr_club_id_f86030_idx"),
        ),
        migrations.AddIndex(
            model_name="trainerpayrollperiodclose",
            index=models.Index(fields=["club", "closed_at"], name="trainers_tr_club_id_699e4e_idx"),
        ),
        migrations.AddConstraint(
            model_name="trainerpayrollperiodclose",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="trainer_payroll_close_valid_period",
            ),
        ),
    ]
