# Generated by Django 5.2.14 on 2026-06-24 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_checkin_subscription_component'),
        ('billing', '0022_subscription_trainer_payout_policy_snapshot_and_more'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('trainers', '0011_trainer_payroll_period_close'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainerearning',
            name='unique_sale_earning_per_payment',
        ),
        migrations.AddField(
            model_name='trainerearning',
            name='component_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerearning',
            name='component_paid_amount_basis_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainerearning',
            name='payout_policy_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trainerearning',
            name='subscription_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainer_earnings', to='billing.subscriptioncomponent'),
        ),
        migrations.AddConstraint(
            model_name='trainerearning',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False), ('subscription_component__isnull', True)), fields=('payment',), name='unique_legacy_sale_earning_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='trainerearning',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False), ('subscription_component__isnull', False)), fields=('payment', 'subscription_component'), name='unique_sale_earning_per_payment_component'),
        ),
    ]
