# Generated by Django 5.2.14 on 2026-07-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_manual_correction_source_earning(apps, schema_editor):
    TrainerEarning = apps.get_model("trainers", "TrainerEarning")
    TrainerEarningAdjustment = apps.get_model("trainers", "TrainerEarningAdjustment")

    group_ids = (
        TrainerEarningAdjustment.objects.filter(
            kind="manual_adjustment",
            source_earning_id__isnull=True,
            correction_group_id__isnull=False,
        )
        .values_list("correction_group_id", flat=True)
        .distinct()
    )
    for group_id in group_ids.iterator():
        rows = list(
            TrainerEarningAdjustment.objects.filter(
                kind="manual_adjustment",
                correction_group_id=group_id,
                source_earning_id__isnull=True,
            ).order_by("id")
        )
        debit = next((row for row in rows if row.direction == "debit"), None)
        if debit is None:
            continue
        candidates = TrainerEarning.objects.filter(
            club_id=debit.club_id,
            trainer_id=debit.trainer_id,
            cancelled=False,
        )
        if debit.source_checkin_id:
            candidates = candidates.filter(checkin_id=debit.source_checkin_id)
        elif debit.source_payment_id:
            candidates = candidates.filter(payment_id=debit.source_payment_id)
        else:
            continue
        candidate_ids = list(candidates.values_list("id", flat=True)[:2])
        if len(candidate_ids) != 1:
            continue
        TrainerEarningAdjustment.objects.filter(id__in=[row.id for row in rows]).update(
            source_earning_id=candidate_ids[0]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_schedule_end_after_start'),
        ('billing', '0027_payment_conversion_enrollment_and_more'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('trainers', '0012_remove_trainerearning_unique_sale_earning_per_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerearningadjustment',
            name='source_earning',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='refund_adjustments',
                to='trainers.trainerearning',
            ),
        ),
        migrations.AddField(
            model_name='trainerearningadjustment',
            name='source_refund',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='trainer_earning_adjustments',
                to='billing.paymentrefund',
            ),
        ),
        migrations.AlterField(
            model_name='trainerearningadjustment',
            name='kind',
            field=models.CharField(
                choices=[
                    ('package_transfer', 'Package transfer'),
                    ('manual_adjustment', 'Manual adjustment'),
                    ('reversal', 'Reversal'),
                    ('refund', 'Payment refund'),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            backfill_manual_correction_source_earning,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='trainerearningadjustment',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('kind', 'refund'),
                    ('source_earning__isnull', False),
                    ('source_refund__isnull', False),
                ),
                fields=('club', 'source_refund', 'source_earning', 'trainer'),
                name='unique_refund_adjustment_per_earning_trainer',
            ),
        ),
    ]
