# Generated by Django 5.2.14 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0021_personal_drop_in_booking"),
        ("billing", "0029_debt_required_tariff"),
        ("trainers", "0013_trainerearningadjustment_source_earning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerearningadjustment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("package_transfer", "Package transfer"),
                    ("manual_adjustment", "Manual adjustment"),
                    ("reversal", "Reversal"),
                    ("refund", "Payment refund"),
                    ("late_drop_in_credit", "Late drop-in settlement credit"),
                    ("checkin_cancellation_debit", "Check-in cancellation debit"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="trainerearningadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind", "late_drop_in_credit"),
                    ("source_checkin__isnull", False),
                    ("source_payment__isnull", False),
                ),
                fields=("club", "source_checkin", "source_payment", "trainer", "kind", "direction"),
                name="unique_late_dropin_credit",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainerearningadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind", "checkin_cancellation_debit"),
                    ("source_checkin__isnull", False),
                    ("source_earning__isnull", False),
                ),
                fields=("club", "source_checkin", "source_earning", "trainer", "kind", "direction"),
                name="unique_checkin_cancel_earning_debit",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainerearningadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind", "checkin_cancellation_debit"),
                    ("reversal_of__isnull", False),
                    ("source_checkin__isnull", False),
                ),
                fields=("club", "source_checkin", "reversal_of", "trainer", "kind", "direction"),
                name="unique_checkin_cancel_late_debit",
            ),
        ),
    ]
