# Generated by Django 5.2.14 on 2026-09-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0014_personal_drop_in_adjustments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerpackageallocation',
            name='source',
            field=models.CharField(choices=[('payment', 'Payment'), ('opening', 'Reviewed opening import'), ('manual_subscription', 'Manual subscription'), ('manual_transfer', 'Manual transfer')], default='manual_subscription', max_length=32),
        ),
    ]
