# Generated by Django 5.2.14 on 2026-09-08 07:32

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_commercialjourneyprotocoltransition'),
        ('trainers', '0015_opening_package_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerSettlementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('opening', 'Начальная сверка'), ('opening_correction', 'Исправление начальной сверки'), ('payout', 'Выплата'), ('payout_reversal', 'Отмена выплаты')], max_length=24)),
                ('effective_on', models.DateField()),
                ('balance_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=12)),
                ('reason', models.TextField()),
                ('channel', models.CharField(default='admin', max_length=16)),
                ('source_namespace', models.CharField(max_length=120)),
                ('source_key', models.CharField(max_length=160)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('command_payload', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_settlement_entries', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent_entries', to='trainers.trainersettlemententry')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='trainers.trainersettlemententry')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_entries', to='trainers.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSettlementReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=180)),
                ('effective_on', models.DateField()),
                ('suggested_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('evidence', models.JSONField(default=dict)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='trainers.trainersettlemententry')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_reconciliations', to='trainers.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSettlementResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('already_included', 'Уже учтено'), ('adjust_opening', 'Исправить остаток')], max_length=24)),
                ('reason', models.TextField()),
                ('source_namespace', models.CharField(max_length=120)),
                ('source_key', models.CharField(max_length=160)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('command_payload', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_resolutions', to=settings.AUTH_USER_MODEL)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='trainers.trainersettlementreconciliation')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('correction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_resolution', to='trainers.trainersettlemententry')),
            ],
        ),
        migrations.AddIndex(
            model_name='trainersettlemententry',
            index=models.Index(fields=['club', 'trainer', 'effective_on'], name='trainers_tr_club_id_e0b208_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainersettlemententry',
            constraint=models.UniqueConstraint(fields=('club', 'source_namespace', 'kind', 'source_key'), name='settlement_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='trainersettlemententry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'opening')), fields=('club', 'trainer'), name='settlement_one_opening'),
        ),
        migrations.AddConstraint(
            model_name='trainersettlemententry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', True), ('kind', 'opening'), ('opening__isnull', True), ('payment_method', ''), ('reversal_of__isnull', True)), models.Q(('amount__isnull', True), ('kind', 'opening_correction'), ('opening__isnull', False), ('payment_method', ''), ('reversal_of__isnull', True)), models.Q(('amount__gt', 0), ('amount__isnull', False), ('balance_delta', django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.Value(-1))), ('kind', 'payout'), ('opening__isnull', False), ('payment_method__in', ['cash', 'transfer']), ('reversal_of__isnull', True)), models.Q(('amount__gt', 0), ('amount__isnull', False), ('balance_delta', models.F('amount')), ('kind', 'payout_reversal'), ('opening__isnull', False), ('payment_method', ''), ('reversal_of__isnull', False)), _connector='OR'), name='settlement_typed_effect'),
        ),
        migrations.AddIndex(
            model_name='trainersettlementreconciliation',
            index=models.Index(fields=['club', 'trainer'], name='trainers_tr_club_id_3f0a8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainersettlementreconciliation',
            constraint=models.UniqueConstraint(fields=('club', 'trainer', 'event_key'), name='settlement_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='trainersettlementresolution',
            constraint=models.UniqueConstraint(fields=('club', 'source_namespace', 'source_key'), name='settlement_resolution_unique'),
        ),
        migrations.AddConstraint(
            model_name='trainersettlementresolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'already_included'), ('correction__isnull', True)), models.Q(('action', 'adjust_opening'), ('correction__isnull', False)), _connector='OR'), name='settlement_resolution_kind'),
        ),
    ]
