# Generated by Django 5.2.12 on 2026-03-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_clubsettings'),
        ('students', '0002_student_last_visit_date'),
        ('trainers', '0002_trainerearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red'), ('churned', 'Churned')], max_length=20)),
                ('due_date', models.DateField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('auto_checkin', 'Student returned'), ('manual_contacted', "Contacted, won't come"), ('manual_other', 'Other')], default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_tasks', to='students.student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_tasks', to='trainers.trainer')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'trainer', 'resolved_at'], name='retention_r_club_id_b3d664_idx'), models.Index(fields=['club', 'student', 'resolved_at'], name='retention_r_club_id_2ea3e9_idx')],
            },
        ),
    ]
