# Generated by Django 5.2.12 on 2026-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubsettings'),
        ('retention', '0001_initial'),
        ('students', '0002_student_last_visit_date'),
        ('trainers', '0002_trainerearning'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='retentiontask',
            index=models.Index(fields=['club', 'resolved_at', 'due_date'], name='retention_r_club_id_278f3d_idx'),
        ),
    ]
