# Generated by Django 5.2.12 on 2026-04-10 09:05

from django.db import migrations, models


def deduplicate_open_tasks(apps, schema_editor):
    """Close duplicate open retention tasks, keeping the newest one."""
    RetentionTask = apps.get_model("retention", "RetentionTask")
    from django.db.models import Count, Max
    from django.utils import timezone

    dupes = (
        RetentionTask.objects.filter(resolved_at__isnull=True)
        .values("club_id", "student_id", "task_type")
        .annotate(cnt=Count("id"), max_id=Max("id"))
        .filter(cnt__gt=1)
    )
    now = timezone.now()
    for group in dupes:
        RetentionTask.objects.filter(
            club_id=group["club_id"],
            student_id=group["student_id"],
            task_type=group["task_type"],
            resolved_at__isnull=True,
        ).exclude(id=group["max_id"]).update(
            resolved_at=now,
            resolution="manual_other",
            status="closed",
        )


def reverse_deduplicate(apps, schema_editor):
    """No-op: cannot un-close tasks."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_min_trainings_to_freeze'),
        ('retention', '0004_retentiontask_status_taskcomment'),
        ('students', '0006_task_type_attempt_count'),
        ('trainers', '0008_remove_legacy_rate_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentiontask',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retentiontask',
            name='task_type',
            field=models.CharField(choices=[('retention', 'Retention'), ('new_lead', 'New Lead'), ('post_trial', 'Post Trial'), ('renewal', 'Renewal')], default='retention', max_length=20),
        ),
        migrations.AlterField(
            model_name='retentiontask',
            name='level',
            field=models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('red', 'Red'), ('churned', 'Churned')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='retentiontask',
            index=models.Index(fields=['club', 'student', 'task_type', 'resolved_at'], name='retention_r_club_id_493be0_idx'),
        ),
        # Deduplicate before adding the unique constraint
        migrations.RunPython(deduplicate_open_tasks, reverse_deduplicate),
        migrations.AddConstraint(
            model_name='retentiontask',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('club', 'student', 'task_type'), name='unique_open_task_per_type_per_student'),
        ),
    ]
