# Generated by Django 5.2.12 on 2026-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0005_task_type_attempt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retentiontask',
            name='resolution',
            field=models.CharField(blank=True, choices=[('auto_checkin', 'Student returned'), ('auto_subscription', 'Subscription created'), ('manual_contacted', "Contacted, won't come"), ('manual_other', 'Other'), ('called_will_come', 'Called, will come'), ('no_answer', 'No answer'), ('quit', 'Quit')], default='', max_length=30),
        ),
    ]
