# Generated by Django 5.2.12 on 2026-03-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('students', '0002_student_last_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('min_trainings', models.PositiveIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('grade_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='grades.gradesystem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainings_since_last_grade', models.PositiveIntegerField(default=0)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('current_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='grades.grade')),
                ('grade_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_grades', to='grades.gradesystem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_grades', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gradesystem',
            constraint=models.UniqueConstraint(fields=('club', 'discipline'), name='unique_grade_system_per_club_discipline'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('grade_system', 'order'), name='unique_grade_order_per_system'),
        ),
        migrations.AddConstraint(
            model_name='studentgrade',
            constraint=models.UniqueConstraint(fields=('student', 'grade_system'), name='unique_student_per_grade_system'),
        ),
    ]
