# Generated by Django 5.2.12 on 2026-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubsettings'),
        ('grades', '0001_initial'),
        ('students', '0002_student_last_visit_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['club', 'student'], name='grades_stud_club_id_fad035_idx'),
        ),
    ]
