# Generated by Django 5.2.12 on 2026-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_add_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='last_counted_checkin_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
