# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_add_one_time_date"),
        ("grades", "0003_add_last_counted_checkin_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeProgressEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_progress_events",
                        to="attendance.checkin",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="clubs.club",
                    ),
                ),
                (
                    "student_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_events",
                        to="grades.studentgrade",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["club", "checkin"], name="grades_grad_club_id_94246c_idx"),
                    models.Index(fields=["club", "student_grade"], name="grades_grad_club_id_96045f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("club", "student_grade", "checkin"),
                        name="unique_grade_progress_event_per_checkin",
                    ),
                ],
            },
        ),
    ]
