# Generated by Django 5.2.12 on 2026-03-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='clubs.location')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='trainers.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('substitute', 'Substitute')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='attendance.schedule')),
                ('substitute_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='trainers.trainer')),
            ],
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['club', 'day_of_week'], name='attendance__club_id_02f281_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.UniqueConstraint(fields=('schedule', 'date'), name='unique_exception_per_schedule_date'),
        ),
    ]
