# Generated by Django 5.2.12 on 2026-03-19 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('clubs', '0001_initial'),
        ('students', '0002_student_last_visit_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('attendee_count', models.PositiveIntegerField(default=0)),
                ('topic_tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('kiosk', 'Kiosk'), ('batch', 'Batch'), ('manual', 'Manual')], max_length=20)),
                ('is_debt', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_checkins', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.location')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='attendance.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='students.student')),
            ],
        ),
    ]
