# Generated by Django 5.2.12 on 2026-03-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_groupsession_checkin'),
        ('billing', '0001_initial'),
        ('clubs', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainers.trainer'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.trainingtype'),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='attendance.schedule'),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainers.trainer'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['club', 'date'], name='attendance__club_id_db6331_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['club', 'student', 'date'], name='attendance__club_id_43a2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['club', 'schedule', 'date'], name='attendance__club_id_8e02b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('student', 'schedule', 'date'), name='unique_checkin_per_student_schedule_date'),
        ),
        migrations.AddConstraint(
            model_name='groupsession',
            constraint=models.UniqueConstraint(fields=('schedule', 'date'), name='unique_group_session_per_schedule_date'),
        ),
    ]
