# Generated by Django 5.2.12 on 2026-03-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_checkin_subscription_checkin_trainer_and_more'),
        ('clubs', '0005_clubsettings_branding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pin_code', models.CharField(blank=True, default='', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kiosk_devices', to='clubs.club')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'is_active'], name='attendance__club_id_d23c35_idx')],
            },
        ),
    ]
