# Generated by Django 5.2.12 on 2026-03-30 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_kioskdevice'),
        ('billing', '0006_allow_null_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='training_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='billing.trainingtype'),
        ),
    ]
