# Generated by Django 5.2.12 on 2026-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_training_type_to_schedule'),
        ('billing', '0006_allow_null_expires_at'),
        ('clubs', '0005_clubsettings_branding_fields'),
        ('trainers', '0004_add_one_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='one_time_date',
            field=models.DateField(blank=True, help_text='If set, slot appears only on this date (not recurring weekly)', null=True),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['club', 'one_time_date'], name='attendance__club_id_243f6e_idx'),
        ),
    ]
