# Generated by Django 5.2.14 on 2026-06-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_one_time_date'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('students', '0006_task_type_attempt_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('frozen', 'Frozen'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('trial_at', models.DateTimeField(blank=True, null=True)),
                ('created_from', models.CharField(choices=[('manual', 'Manual'), ('lead_booking', 'Lead booking'), ('import', 'Import')], default='manual', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='attendance.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_enrollments', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'schedule', 'status'], name='attendance__club_id_d8dbf9_idx'), models.Index(fields=['club', 'student', 'status'], name='attendance__club_id_2222d2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True), ('status__in', ['active', 'trial', 'frozen'])), fields=('club', 'student', 'schedule'), name='uniq_open_schedule_enrollment')],
            },
        ),
    ]
