# Generated by Codex on 2026-06-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_scheduleenrollment"),
        ("clubs", "0007_min_trainings_to_freeze"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckinCascadeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("grade_progress", "Grade progress"),
                            ("group_analytics", "Group analytics"),
                            ("parent_notification", "Parent notification"),
                            ("retention_auto_close", "Retention auto close"),
                            ("post_trial_task", "Post-trial task"),
                            ("trainings_left_push", "Trainings-left push"),
                        ],
                        max_length=40,
                    ),
                ),
                ("status", models.CharField(choices=[("queued", "Queued")], default="queued", max_length=20)),
                ("expected", models.BooleanField(default=True)),
                ("task_name", models.CharField(max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cascade_events",
                        to="attendance.checkin",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["club", "checkin", "status"],
                        name="attendance__club_id_d0db28_idx",
                    ),
                    models.Index(
                        fields=["club", "effect", "status"],
                        name="attendance__club_id_305df7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("club", "checkin", "effect"),
                        name="unique_checkin_cascade_effect",
                    ),
                ],
            },
        ),
    ]
