# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_checkincascadeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskdevice",
            name="activation_failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="activation_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="pin_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="kioskdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("pin_code__gt", "")),
                fields=("pin_code",),
                name="uniq_active_kiosk_pin_code",
            ),
        ),
    ]
