# Generated by Django 5.2.14 on 2026-06-20 18:33

import django.db.models.deletion
from django.conf import settings
from django.db.models import Count
from django.db import migrations, models


def assert_no_duplicate_one_time_trainer_slots(apps, schema_editor):
    Schedule = apps.get_model('attendance', 'Schedule')
    duplicate = (
        Schedule.objects
        .filter(one_time_date__isnull=False)
        .values('club_id', 'trainer_id', 'one_time_date', 'start_time', 'end_time')
        .annotate(row_count=Count('id'))
        .filter(row_count__gt=1)
        .order_by('club_id', 'trainer_id', 'one_time_date', 'start_time', 'end_time')
        .first()
    )
    if duplicate:
        raise RuntimeError(
            'Duplicate one-time schedule trainer slot exists; resolve duplicates before applying '
            'attendance migration 0010.'
        )


def assert_no_duplicate_dated_enrollments(apps, schema_editor):
    ScheduleEnrollment = apps.get_model('attendance', 'ScheduleEnrollment')
    duplicate = (
        ScheduleEnrollment.objects
        .filter(
            starts_on__isnull=False,
            ends_on__isnull=False,
            status__in=['active', 'trial', 'frozen'],
        )
        .values('club_id', 'student_id', 'schedule_id', 'starts_on', 'ends_on')
        .annotate(row_count=Count('id'))
        .filter(row_count__gt=1)
        .order_by('club_id', 'student_id', 'schedule_id', 'starts_on', 'ends_on')
        .first()
    )
    if duplicate:
        raise RuntimeError(
            'Duplicate dated schedule enrollment exists; resolve duplicates before applying '
            'attendance migration 0010.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_kiosk_activation_hardening'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('students', '0007_accountaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assert_no_duplicate_one_time_trainer_slots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('one_time_date__isnull', False)), fields=('club', 'trainer', 'one_time_date', 'start_time', 'end_time'), name='uniq_one_time_schedule_trainer_slot'),
        ),
        migrations.CreateModel(
            name='ScheduleBookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('guest_visit_booked', 'Guest visit booked'), ('personal_session_booked', 'Personal session booked')], db_index=True, max_length=32)),
                ('origin', models.CharField(choices=[('planned_session_action', 'Planned session action'), ('walk_in_checkin', 'Walk-in check-in'), ('student_self_booking', 'Student self-booking')], max_length=32)),
                ('effective_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduleenrollment',
            name='created_from',
            field=models.CharField(choices=[('manual', 'Manual'), ('lead_booking', 'Lead booking'), ('guest_visit', 'Guest visit'), ('personal_booking', 'Personal booking'), ('student_self_booking', 'Student self-booking'), ('paid_conversion', 'Paid conversion'), ('import', 'Import')], default='manual', max_length=20),
        ),
        migrations.RunPython(assert_no_duplicate_dated_enrollments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='scheduleenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', False), ('starts_on__isnull', False), ('status__in', ['active', 'trial', 'frozen'])), fields=('club', 'student', 'schedule', 'starts_on', 'ends_on'), name='uniq_dated_schedule_enrollment'),
        ),
        migrations.AddField(
            model_name='schedulebookingevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_booking_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulebookingevent',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='schedulebookingevent',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_events', to='attendance.scheduleenrollment'),
        ),
        migrations.AddField(
            model_name='schedulebookingevent',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_events', to='attendance.schedule'),
        ),
        migrations.AddField(
            model_name='schedulebookingevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_booking_events', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='schedulebookingevent',
            index=models.Index(fields=['club', 'schedule', 'effective_date'], name='attendance__club_id_089ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulebookingevent',
            index=models.Index(fields=['club', 'student', 'created_at'], name='attendance__club_id_33d861_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulebookingevent',
            index=models.Index(fields=['club', 'event_type', 'created_at'], name='attendance__club_id_204b15_idx'),
        ),
    ]
