# Generated by Django 5.2.14 on 2026-06-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_schedulebookingevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulebookingevent',
            name='origin',
            field=models.CharField(choices=[('planned_session_action', 'Planned session action'), ('walk_in_checkin', 'Walk-in check-in'), ('student_self_booking', 'Student self-booking'), ('parent_self_booking', 'Parent self-booking')], max_length=32),
        ),
    ]
