# Generated by Django 5.2.14 on 2026-06-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_schedulebookingevent_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulebookingevent',
            name='event_type',
            field=models.CharField(choices=[('guest_visit_booked', 'Guest visit booked'), ('personal_session_booked', 'Personal session booked'), ('guest_visit_cancelled', 'Guest visit cancelled'), ('personal_session_cancelled', 'Personal session cancelled')], db_index=True, max_length=32),
        ),
    ]
