# Generated by Django 5.2.14 on 2026-06-21 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_add_booking_cancellation_events'),
        ('billing', '0021_payment_package_owner_trainer'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('trainers', '0009_trainer_package_compensation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='published', max_length=20)),
                ('booked_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_availability_slots', to='attendance.scheduleenrollment')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_availability_slots', to='clubs.location')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_availability_slots', to='trainers.trainer')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_availability_slots', to='billing.trainingtype')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'status', 'starts_at'], name='attendance__club_id_25725e_idx'), models.Index(fields=['club', 'trainer', 'starts_at'], name='attendance__club_id_c6a973_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='attendance_personal_slot_ends_after_start'), models.UniqueConstraint(condition=models.Q(('status__in', ['published', 'booked'])), fields=('club', 'trainer', 'starts_at', 'ends_at'), name='uniq_active_personal_availability_trainer_slot')],
            },
        ),
    ]
