# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_personal_availability_slot"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="schedule",
            name="uniq_one_time_schedule_trainer_slot",
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("club", "trainer", "one_time_date", "start_time", "end_time"),
                condition=models.Q(one_time_date__isnull=False, is_active=True),
                name="uniq_one_time_schedule_trainer_slot",
            ),
        ),
    ]
