# Generated by Django 5.2.14 on 2026-06-24 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_active_one_time_schedule_slot_constraint'),
        ('billing', '0022_subscription_trainer_payout_policy_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='subscription_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='billing.subscriptioncomponent'),
        ),
    ]
