# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0015_checkin_subscription_component"),
        ("billing", "0023_subscription_renewal_chain_id_and_more"),
        ("clubs", "0007_min_trainings_to_freeze"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trainers", "0009_trainer_package_compensation"),
        ("students", "0005_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalavailabilityslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("held", "Held"),
                    ("booked", "Booked"),
                    ("cancelled", "Cancelled"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="personalavailabilityslot",
            name="uniq_active_personal_availability_trainer_slot",
        ),
        migrations.AddConstraint(
            model_name="personalavailabilityslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["published", "held", "booked"])),
                fields=("club", "trainer", "starts_at", "ends_at"),
                name="uniq_active_personal_availability_trainer_slot",
            ),
        ),
        migrations.CreateModel(
            name="PersonalBookingPaymentReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("booked", "Booked"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("manual_review", "Manual review"),
                        ],
                        default="pending_payment",
                        max_length=30,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=120)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=120)),
                ("last_error_message", models.TextField(blank=True, default="")),
                (
                    "availability_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservations",
                        to="attendance.personalavailabilityslot",
                    ),
                ),
                (
                    "bank_payment_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservation",
                        to="billing.bankpaymentorder",
                    ),
                ),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="%(class)ss", to="clubs.club")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_personal_payment_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservation",
                        to="attendance.scheduleenrollment",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservations",
                        to="clubs.location",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservation",
                        to="billing.payment",
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservation",
                        to="attendance.schedule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservations",
                        to="students.student",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservation",
                        to="billing.subscription",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservations",
                        to="billing.tariff",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservations",
                        to="trainers.trainer",
                    ),
                ),
                (
                    "training_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_payment_reservations",
                        to="billing.trainingtype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["club", "status", "expires_at"], name="attendance_ppr_status_idx"),
                    models.Index(fields=["club", "trainer", "starts_at"], name="attendance_ppr_trainer_idx"),
                    models.Index(fields=["club", "student", "created_at"], name="attendance_ppr_student_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="attendance_personal_payment_reservation_ends_after_start",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending_payment", "booked"])),
                        fields=("club", "trainer", "starts_at", "ends_at"),
                        name="uniq_active_personal_payment_reservation_slot",
                    ),
                    models.UniqueConstraint(
                        condition=~models.Q(("idempotency_key", "")),
                        fields=("club", "idempotency_key"),
                        name="uniq_personal_payment_reservation_idempotency",
                    ),
                ],
            },
        ),
    ]
