# Generated by Django 5.2.14 on 2026-07-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0020_schedule_end_after_start"),
        ("billing", "0029_debt_required_tariff"),
        ("clubs", "0007_min_trainings_to_freeze"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulebookingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guest_visit_booked", "Guest visit booked"),
                    ("personal_session_booked", "Personal session booked"),
                    ("guest_visit_cancelled", "Guest visit cancelled"),
                    ("personal_session_cancelled", "Personal session cancelled"),
                    ("personal_drop_in_cancelled", "Personal drop-in cancelled"),
                    ("personal_drop_in_no_show", "Personal drop-in no-show"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="scheduleenrollment",
            name="created_from",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("lead_booking", "Lead booking"),
                    ("guest_visit", "Guest visit"),
                    ("personal_booking", "Personal booking"),
                    ("personal_drop_in", "Personal drop-in"),
                    ("student_self_booking", "Student self-booking"),
                    ("paid_conversion", "Paid conversion"),
                    ("import", "Import"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PersonalDropInBooking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tariff_name_snapshot", models.CharField(max_length=200)),
                ("price_snapshot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("state", models.CharField(choices=[("scheduled", "Scheduled"), ("attended", "Attended"), ("cancelled", "Cancelled"), ("no_show", "No show")], default="scheduled", max_length=20)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("checkin", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="personal_drop_in_booking", to="attendance.checkin")),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="%(class)ss", to="clubs.club")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_personal_drop_in_bookings", to=settings.AUTH_USER_MODEL)),
                ("debt", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="personal_drop_in_booking", to="billing.debt")),
                ("enrollment", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="personal_drop_in_booking", to="attendance.scheduleenrollment")),
                ("tariff", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="personal_drop_in_bookings", to="billing.tariff")),
            ],
        ),
        migrations.CreateModel(
            name="PersonalDropInPaymentLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("bank_payment_order", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="personal_drop_in_payment_link", to="billing.bankpaymentorder")),
                ("booking", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_links", to="attendance.personaldropinbooking")),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="%(class)ss", to="clubs.club")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_personal_drop_in_payment_links", to=settings.AUTH_USER_MODEL)),
                ("payment", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="personal_drop_in_payment_link", to="billing.payment")),
            ],
        ),
        migrations.AddIndex(
            model_name="personaldropinbooking",
            index=models.Index(fields=["club", "state", "created_at"], name="attendance__club_id_19a3ef_idx"),
        ),
        migrations.AddIndex(
            model_name="personaldropinbooking",
            index=models.Index(fields=["club", "tariff", "state"], name="attendance__club_id_d12592_idx"),
        ),
        migrations.AddConstraint(
            model_name="personaldropinbooking",
            constraint=models.CheckConstraint(condition=models.Q(("price_snapshot__gt", 0)), name="attendance_dropin_price_positive"),
        ),
        migrations.AddConstraint(
            model_name="personaldropinbooking",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("checkin__isnull", False), ("state", "attended")), models.Q(("state", "attended"), _negated=True), _connector="OR"), name="attendance_dropin_attended_checkin"),
        ),
        migrations.AddConstraint(
            model_name="personaldropinbooking",
            constraint=models.CheckConstraint(condition=models.Q(models.Q(("state__in", ["scheduled", "cancelled", "no_show"]), _negated=True), models.Q(("checkin__isnull", True), ("debt__isnull", True)), _connector="OR"), name="attendance_dropin_terminal_no_finance"),
        ),
        migrations.AddConstraint(
            model_name="personaldropinbooking",
            constraint=models.UniqueConstraint(fields=("club", "idempotency_key"), name="uniq_personal_dropin_booking_idempotency"),
        ),
        migrations.AddIndex(
            model_name="personaldropinpaymentlink",
            index=models.Index(fields=["club", "booking", "created_at"], name="attendance__club_id_6480a1_idx"),
        ),
        migrations.AddConstraint(
            model_name="personaldropinpaymentlink",
            constraint=models.UniqueConstraint(fields=("club", "idempotency_key"), name="uniq_personal_dropin_payment_link_idempotency"),
        ),
    ]
