# Generated by Django 5.2.14 on 2026-07-27 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_off_rollout_states(apps, schema_editor):
    Club = apps.get_model("clubs", "Club")
    TrainingGroupRolloutState = apps.get_model("attendance", "TrainingGroupRolloutState")
    existing_club_ids = TrainingGroupRolloutState.objects.values_list("club_id", flat=True)
    TrainingGroupRolloutState.objects.bulk_create(
        [
            TrainingGroupRolloutState(club_id=club_id, mode="off")
            for club_id in Club.objects.exclude(id__in=existing_club_ids).values_list("id", flat=True)
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_personal_drop_in_booking'),
        ('billing', '0029_debt_required_tariff'),
        ('clubs', '0007_min_trainings_to_freeze'),
        ('students', '0009_student_guardian_phone'),
        ('trainers', '0014_personal_drop_in_adjustments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleenrollment',
            name='created_from',
            field=models.CharField(choices=[('manual', 'Manual'), ('lead_booking', 'Lead booking'), ('guest_visit', 'Guest visit'), ('personal_booking', 'Personal booking'), ('personal_drop_in', 'Personal drop-in'), ('student_self_booking', 'Student self-booking'), ('paid_conversion', 'Paid conversion'), ('group_projection', 'Group projection'), ('import', 'Import')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_training_groups', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_groups', to='clubs.location')),
                ('responsible_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_training_groups', to='trainers.trainer')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_groups', to='billing.trainingtype')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='training_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='attendance.traininggroup'),
        ),
        migrations.CreateModel(
            name='TrainingGroupMappingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('batch_id', models.UUIDField()),
                ('action', models.CharField(max_length=40)),
                ('previous_group_snapshot', models.JSONField(blank=True, default=dict)),
                ('new_group_snapshot', models.JSONField(blank=True, default=dict)),
                ('rationale', models.CharField(max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_group_mapping_events', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_group_mapping_events', to='attendance.schedule')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_events', to='attendance.traininggroup')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('paid_conversion', 'Paid conversion'), ('import', 'Import'), ('migration', 'Migration'), ('transfer', 'Transfer')], max_length=20)),
                ('authority', models.CharField(choices=[('independent', 'Independent'), ('payment_owned', 'Payment owned')], default='independent', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_training_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_group_memberships', to='students.student')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='attendance.traininggroup')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleenrollment',
            name='training_group_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_enrollment_projections', to='attendance.traininggroupmembership'),
        ),
        migrations.CreateModel(
            name='TrainingGroupMembershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=40)),
                ('effective_date', models.DateField()),
                ('previous_state_snapshot', models.JSONField(blank=True, default=dict)),
                ('new_state_snapshot', models.JSONField(blank=True, default=dict)),
                ('rationale', models.CharField(max_length=500)),
                ('source_enrollment_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_payment_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_group_membership_events', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='attendance.traininggroupmembership')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroupRolloutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('previous_mode', models.CharField(choices=[('off', 'Off'), ('reconciling', 'Reconciling'), ('shadow', 'Shadow'), ('active', 'Active'), ('containment', 'Containment')], max_length=20)),
                ('new_mode', models.CharField(choices=[('off', 'Off'), ('reconciling', 'Reconciling'), ('shadow', 'Shadow'), ('active', 'Active'), ('containment', 'Containment')], max_length=20)),
                ('rationale', models.CharField(max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_group_rollout_events', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroupRolloutState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('off', 'Off'), ('reconciling', 'Reconciling'), ('shadow', 'Shadow'), ('active', 'Active'), ('containment', 'Containment')], default='off', max_length=20)),
                ('reconciling_from_mode', models.CharField(blank=True, choices=[('off', 'Off'), ('reconciling', 'Reconciling'), ('shadow', 'Shadow'), ('active', 'Active'), ('containment', 'Containment')], default='', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
        ),
        migrations.AddIndex(
            model_name='traininggroup',
            index=models.Index(fields=['club', 'status'], name='att_group_club_status_idx'),
        ),
        migrations.AddIndex(
            model_name='traininggroup',
            index=models.Index(fields=['club', 'training_type', 'location'], name='att_group_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='traininggroupmappingevent',
            index=models.Index(fields=['club', 'batch_id'], name='att_mapping_event_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='traininggroupmappingevent',
            index=models.Index(fields=['club', 'training_group', 'created_at'], name='att_mapping_event_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='traininggroupmappingevent',
            constraint=models.UniqueConstraint(fields=('club', 'idempotency_key'), name='uniq_training_group_mapping_event_key'),
        ),
        migrations.AddIndex(
            model_name='traininggroupmembership',
            index=models.Index(fields=['club', 'training_group', 'status'], name='att_groupmem_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='traininggroupmembership',
            index=models.Index(fields=['club', 'student', 'status'], name='att_groupmem_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='traininggroupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='att_group_membership_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='traininggroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True), ('status__in', ['active', 'frozen'])), fields=('club', 'student', 'training_group'), name='uniq_open_training_group_membership'),
        ),
        migrations.AddIndex(
            model_name='traininggroupmembershipevent',
            index=models.Index(fields=['club', 'membership', 'created_at'], name='att_member_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='traininggroupmembershipevent',
            constraint=models.UniqueConstraint(fields=('club', 'idempotency_key'), name='uniq_training_group_membership_event_key'),
        ),
        migrations.AddIndex(
            model_name='traininggrouprolloutevent',
            index=models.Index(fields=['club', 'created_at'], name='att_rollout_event_club_idx'),
        ),
        migrations.AddConstraint(
            model_name='traininggrouprolloutevent',
            constraint=models.UniqueConstraint(fields=('club', 'idempotency_key'), name='uniq_training_group_rollout_event_key'),
        ),
        migrations.AddConstraint(
            model_name='traininggrouprolloutstate',
            constraint=models.UniqueConstraint(fields=('club',), name='uniq_training_group_rollout_per_club'),
        ),
        migrations.RunPython(create_off_rollout_states, migrations.RunPython.noop),
    ]
