# Generated by Django 5.2.14 on 2026-09-01 07:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_personal_self_service_command'),
        ('clubs', '0008_clubsettings_unified_client_journey_enabled'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personalservicetermssnapshot',
            name='attendance_personal_terms_zero_discount',
        ),
        migrations.AddField(
            model_name='personalservicetermssnapshot',
            name='discount_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalservicetermssnapshot',
            name='discount_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personalservicetermssnapshot',
            name='discount_type_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='personalservicetermssnapshot',
            name='discount_value_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalservicetermssnapshot',
            name='terms_version',
            field=models.CharField(choices=[('complete_v1', 'Complete v1'), ('complete_v2', 'Complete v2'), ('legacy_partial', 'Legacy partial')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='personalservicetermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('terms_version', 'complete_v2'), ('discount_amount', 0), _connector='OR'), name='attendance_personal_terms_legacy_zero_discount'),
        ),
        migrations.AddConstraint(
            model_name='personalservicetermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('terms_version', 'complete_v2'), _negated=True), models.Q(('base_amount__gt', 0), ('discount_amount__gte', 0), ('payable_amount__gt', 0), ('base_amount', django.db.models.expressions.CombinedExpression(models.F('discount_amount'), '+', models.F('payable_amount'))), models.Q(models.Q(('discount_id_snapshot__isnull', True), ('discount_name_snapshot', ''), ('discount_type_snapshot', ''), ('discount_value_snapshot__isnull', True), ('discount_amount', 0)), models.Q(('discount_id_snapshot__isnull', False), models.Q(('discount_name_snapshot', ''), _negated=True), ('discount_type_snapshot__in', ['percent', 'fixed']), ('discount_value_snapshot__gte', 0)), _connector='OR')), _connector='OR'), name='attendance_personal_terms_v2_discount_consistent'),
        ),
    ]
