# Generated by Codex on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0027_remove_personalservicetermssnapshot_attendance_personal_terms_zero_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulebookingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guest_visit_booked", "Guest visit booked"),
                    ("personal_session_booked", "Personal session booked"),
                    ("guest_visit_cancelled", "Guest visit cancelled"),
                    ("personal_session_cancelled", "Personal session cancelled"),
                    ("personal_session_rescheduled", "Personal session rescheduled"),
                    ("personal_drop_in_cancelled", "Personal drop-in cancelled"),
                    ("personal_drop_in_no_show", "Personal drop-in no-show"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
