# Generated by Django 5.2.14 on 2026-09-01 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_schedulebookingevent_personal_session_rescheduled'),
        ('billing', '0046_remove_tariff_uniq_personal_booking_club_default_and_more'),
        ('clubs', '0008_clubsettings_unified_client_journey_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPaymentMethodCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replacement_payment_method', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('command_fingerprint', models.CharField(max_length=64)),
                ('command_shape', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_payment_method_corrections', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('original_bank_payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_payment_method_corrections', to='billing.bankpaymentorder')),
                ('original_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_payment_method_corrections', to='billing.payment')),
                ('original_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_corrections', to='attendance.personalbookingpaymentreservation')),
                ('replacement_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_corrections', to='attendance.personaldropinbooking')),
                ('replacement_payment_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_corrections', to='attendance.personaldropinpaymentlink')),
                ('source_terms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_corrections', to='attendance.personalservicetermssnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'original_reservation', 'created_at'], name='att_method_corr_res_idx'), models.Index(fields=['club', 'original_payment', 'created_at'], name='att_method_corr_pay_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('original_reservation__isnull', False), ('original_payment__isnull', False), _connector='OR'), name='attendance_personal_method_correction_source'), models.UniqueConstraint(fields=('club', 'idempotency_key'), name='uniq_personal_method_correction_idempotency')],
            },
        ),
    ]
