# Generated by Django 5.2.14 on 2026-09-08 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_personalpaymentmethodcorrection'),
        ('clubs', '0010_commercialjourneyprotocoltransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='notification_policy',
            field=models.CharField(choices=[('live', 'Live attendance'), ('silent_correction', 'Silent historical correction'), ('dated_correction', 'Notify with actual attendance date')], default='live', max_length=30),
        ),
        migrations.AddField(
            model_name='checkin',
            name='parent_cancellation_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='parent_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentAttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('record', 'Record attendance'), ('cancel', 'Cancel attendance')], max_length=12)),
                ('channel', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('command_key', models.CharField(max_length=120)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_receipts', to='attendance.checkin')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'checkin', 'created_at'], name='att_correction_history_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'command_key'), name='att_correction_command_uniq'), models.UniqueConstraint(fields=('checkin', 'action'), name='att_correction_action_uniq')],
            },
        ),
    ]
