# Generated by Django 5.2.12 on 2026-03-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubsettings'),
        ('notifications', '0001_initial'),
        ('students', '0002_student_last_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('sub_expiry_7d', 'Subscription expiring (7 days)'), ('sub_expiry_3d', 'Subscription expiring (3 days)'), ('sub_expiry_1d', 'Subscription expiring (1 day)'), ('trainings_left_2', '2 trainings left'), ('trainings_last', 'Last training')], max_length=30)),
                ('title_template', models.CharField(default='{name}, напоминание', max_length=200)),
                ('body_template', models.CharField(max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('days_before', models.PositiveIntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_templates', to='clubs.club')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club', 'trigger_type'), name='unique_template_per_club_trigger')],
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('sent_date', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_notifications', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club', 'student', 'notification_type', 'sent_date'), name='unique_notification_per_student_per_day')],
            },
        ),
    ]
