# Generated by Django 5.2.12 on 2026-03-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubsettings'),
        ('notifications', '0003_register_scheduled_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='clubs.club'),
        ),
    ]
