# Generated by Django 5.2.12 on 2026-03-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_template_tenant_mixin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='trigger_type',
            field=models.CharField(choices=[('sub_expiry_7d', 'Subscription expiring (7 days)'), ('sub_expiry_3d', 'Subscription expiring (3 days)'), ('sub_expiry_1d', 'Subscription expiring (1 day)'), ('trainings_left_2', '2 trainings left'), ('trainings_last', 'Last training'), ('parent_checkin', 'Parent: child checked in'), ('parent_sub_expiry', 'Parent: child subscription expiring'), ('parent_grade_up', 'Parent: child grade promotion'), ('trial_feedback', 'Trial feedback survey')], max_length=30),
        ),
    ]
