# Generated by Django 5.2.12 on 2026-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationtemplate_trigger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='trigger_type',
            field=models.CharField(choices=[('sub_expiry_7d', 'Subscription expiring (7 days)'), ('sub_expiry_3d', 'Subscription expiring (3 days)'), ('sub_expiry_1d', 'Subscription expiring (1 day)'), ('trainings_left_2', '2 trainings left'), ('trainings_last', 'Last training'), ('parent_checkin', 'Parent: child checked in'), ('parent_sub_expiry', 'Parent: child subscription expiring'), ('parent_grade_up', 'Parent: child grade promotion'), ('trial_feedback', 'Trial feedback survey'), ('training_reminder', 'Training reminder (1h before)'), ('missed_training', 'Missed habitual training'), ('follow_up', 'Follow-up task notification'), ('churned_survey', 'Churned student survey')], max_length=30),
        ),
    ]
