# Generated by Django 5.2.14 on 2026-06-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='trigger_type',
            field=models.CharField(
                choices=[
                    ('sub_expiry_7d', 'Абонемент истекает через 7 дней'),
                    ('sub_expiry_3d', 'Абонемент истекает через 3 дня'),
                    ('sub_expiry_1d', 'Абонемент истекает завтра'),
                    ('trainings_left_2', 'Осталось 2 занятия'),
                    ('trainings_last', 'Последнее занятие'),
                    ('parent_checkin', 'Родитель: ребёнок на тренировке'),
                    ('parent_sub_expiry', 'Родитель: абонемент ребёнка истекает'),
                    ('parent_grade_up', 'Родитель: повышение грейда'),
                    ('trial_feedback', 'Отзыв после пробной тренировки'),
                    ('training_reminder', 'Напоминание о тренировке (за 1 час)'),
                    ('missed_training', 'Пропуск привычной тренировки'),
                    ('follow_up', 'Напоминание по задаче'),
                    ('churned_survey', 'Опрос ушедшего ученика'),
                ],
                max_length=30,
            ),
        ),
    ]
